/* ============================================================
   Opsboard — the two dictionaries, English and Arabic.

   Same shape on both sides. `lib/i18n.js` resolves a dotted path against
   the active half and falls back to `en` when a key is missing, so English
   is always the floor: nothing can render blank.

   Values are either strings — `{name}` placeholders are filled from the vars
   object — or functions, used wherever a sentence has to be built rather than
   filled in. Arabic counts noun forms four ways, so anything with a number in
   it is written as a function over `arPlural`.

   What deliberately stays in Latin on the Arabic side: people's names, company
   names, email addresses, phone numbers, URLs, invoice numbers, record ids,
   currency codes and amounts. Those are data, not language.
   ============================================================ */

/* ---------- counted nouns ---------- */

/* English has two forms. Arabic has five slots — nothing, one, a pair, a small
   group (3–10, noun in the plural) and a large one (11+, noun back in the
   singular) — and the adjective agrees with the noun, so each form is written
   out whole rather than assembled from parts. */
export function arPlural(n, f) {
  const a = Math.abs(Number(n) || 0);
  let s;
  if (a === 0) s = f.zero !== undefined ? f.zero : f.many;
  else if (a === 1) s = f.one;
  else if (a === 2) s = f.two;
  else if (a % 100 >= 3 && a % 100 <= 10) s = f.few;
  else s = f.many;
  return String(s).replace(/\{n\}/g, n);
}

export const enPlural = (n, one, many) => `${n} ${n === 1 ? one : many || `${one}s`}`;

/* ---------- english ---------- */

const en = {
  brand: {
    name: 'Opsboard',
    tag: 'Operations platform',
    copilot: 'Opsboard Copilot',
    initials: 'OC',
  },

  nav: {
    overview: 'Overview',
    customers: 'Customers',
    deals: 'Deals',
    invoices: 'Invoices',
    reports: 'Reports',
    team: 'Team and roles',
    settings: 'Settings',
    main: 'Main',
    open: 'Open navigation',
  },
  navGroup: {
    Workspace: 'Workspace',
    Revenue: 'Revenue',
    Administration: 'Administration',
  },

  common: {
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    gotIt: 'Got it',
    details: 'Details',
    remove: 'Remove',
    exportCsv: 'Export CSV',
    closePanel: 'Close panel',
    skip: 'Skip to main content',
    newTab: '{label} — opens in a new tab',
    dash: '—',
    and: ' and ',
    or: ' or ',
    never: 'never',
    notYet: 'not yet',
    always: 'always',
    none: 'none',
    empty: 'Empty',
    read: 'read',
    site: 'nasvih.in',
    github: 'GitHub',
    sourceLink: 'Source on GitHub',
  },

  /* the five reference tables, by stored id */
  stages: {
    qualify: 'Qualify', proposal: 'Proposal', negotiation: 'Negotiation', won: 'Won', lost: 'Lost',
  },
  segments: {
    Retail: 'Retail', Wholesale: 'Wholesale', Institutional: 'Institutional', Online: 'Online', Government: 'Government',
  },
  statuses: {
    active: 'active', 'at-risk': 'at-risk', dormant: 'dormant',
    draft: 'draft', sent: 'sent', overdue: 'overdue', paid: 'paid',
    invited: 'invited', removed: 'removed',
  },
  roles: { owner: 'owner', admin: 'admin', member: 'member', viewer: 'viewer' },
  perms: {
    view: 'View workspace data',
    customers: 'Create and edit customers',
    deals: 'Move deals between stages',
    invoices: 'Issue and settle invoices',
    team: 'Invite people and set roles',
    billing: 'Change plan and billing',
  },
  plans: { starter: 'Starter', growth: 'Growth', scale: 'Scale' },
  currencies: { INR: 'Indian rupee', SAR: 'Saudi riyal', AED: 'UAE dirham' },
  aging: { current: 'Not due', b1: '1–30 days', b2: '31–60 days', b3: '60+ days' },
  months: { January: 'January', April: 'April', July: 'July', October: 'October' },
  quarter: ({ q, y }) => `Q${q} ${y}`,
  activityType: { deal: 'deal', invoice: 'invoice', customer: 'customer', team: 'team', note: 'note' },

  count: {
    invoice: ({ n }) => enPlural(n, 'invoice'),
    openInvoice: ({ n }) => enPlural(n, 'open invoice'),
    issuedInvoice: ({ n }) => enPlural(n, 'issued invoice'),
    deal: ({ n }) => enPlural(n, 'deal'),
    account: ({ n }) => enPlural(n, 'account'),
    change: ({ n }) => enPlural(n, 'change'),
    recordedChange: ({ n }) => enPlural(n, 'recorded change'),
    day: ({ n }) => enPlural(n, 'day'),
    seat: ({ n }) => enPlural(n, 'seat'),
    invite: ({ n }) => enPlural(n, 'invite'),
    notification: ({ n }) => enPlural(n, 'notification'),
  },

  time: {
    now: 'just now',
    m: '{n}m ago',
    h: '{n}h ago',
    d: '{n}d ago',
  },

  side: {
    workspace: 'Workspace',
    choose: 'Choose workspace',
    current: 'Workspace: {name}. Choose another.',
    sub: '{city} · {plan} plan',
    optSub: ({ accounts, people }) => `${accounts} accounts · ${people} people`,
    railCollapse: 'Collapse sidebar',
    railExpand: 'Expand sidebar',
    tone: 'Sidebar colour',
    reset: 'Reset demo data',
    resetBody: 'All three workspaces will be regenerated from the seed. Every edit you have made in this browser will be lost.',
    resetOk: 'Reset everything',
    resetDone: 'Demo data reset',
    note: 'Sample data only. Saved in this browser, never sent anywhere.',
    switched: 'Switched to {name}',
  },

  pwa: {
    install: 'Install app',
    installTitle: 'Install {app} on this device',
    installed: '{app} installed. It opens in its own window from now on.',
    dismissed: 'Install dismissed — the button stays here if you change your mind.',
    ios: 'On iPhone and iPad: tap Share, then "Add to Home Screen".',
    other: 'Use your browser menu and choose "Install app" or "Add to Home screen".',
  },

  top: {
    dark: 'Switch to dark mode',
    light: 'Switch to light mode',
    about: 'About this demo',
    aboutTitle: 'Demo build: all records are generated locally and stored in this browser only. Open for details.',
    previewSize: 'Preview size',
    phone: 'Preview at phone size',
    desktop: 'Desktop view',
    back: 'Back to desktop',
    stageLabel: 'Phone preview',
    frameTitle: 'Opsboard at phone size',
    stageSize: '390 × 844 · the app running inside a frame',
  },

  notifPanel: {
    title: 'Notifications',
    label: 'Notifications',
    labelUnread: 'Notifications, {n} unread',
    labelClear: 'Notifications, nothing unread',
    sub: '{name} · {n} unread',
    markAll: 'Mark all read',
    marked: ({ n }) => `${enPlural(n, 'notification')} marked read`,
    emptyTitle: 'Nothing needs attention',
    emptyBody: 'No invoice in {name} is past due, no deal is closing this week and the plan still has seats. '
      + 'Overdue money, deals reaching their close date, a full plan and anything the team changes all arrive here.',
    foot: 'Built from this workspace as it stands. Read marks are kept in this browser.',
    goto: '{title}. Open {screen}.',
    markRead: 'Mark read',
    markReadOn: 'Mark "{title}" read',
  },

  notify: {
    tagOverdue: 'Overdue',
    tagSlipping: 'Slipping',
    tagClosing: 'Closing',
    tagSeats: 'Seats',
    tagChange: 'Change',
    due: 'due {date}',
    invTitle: ({ number, n }) => `${number} is ${n} ${n === 1 ? 'day' : 'days'} past due`,
    invLine: '{name} owes {amount}. Chase it, or mark it paid when the money lands.',
    invMoreTitle: ({ n }) => `${n} more invoices are past due`,
    invMoreLine: 'A further {amount} sits behind the three above.',
    dealLate: ({ title, n }) => `${title} passed its close date ${n} ${n === 1 ? 'day' : 'days'} ago`,
    dealSoon: ({ title, n }) => `${title} is due to close ${n === 0 ? 'today' : `in ${n} ${n === 1 ? 'day' : 'days'}`}`,
    dealLine: '{amount} at {p}% likely, {owner} owns it. Currently in {stage}.',
    seatsOver: ({ n, plan }) => `${n} seats over the ${plan} plan`,
    seatsLeft: ({ n, total }) => `${n} of ${total} seats left`,
    seatsOverLine: 'Change the plan in Settings, or remove access for someone who has left.',
    seatsLeftLine: 'Invites count against the allowance as soon as they are sent.',
    changeLine: '{actor} · {when}',
  },

  about: {
    title: 'About this demo',
    b1t: 'What this is',
    b1: 'Opsboard is the operations core of a business: one workspace holding its customers, its '
      + 'deal pipeline, its invoices, its team and their roles, and the reports built from all of it. '
      + 'Switch workspace in the sidebar and every screen, count and total re-scopes to that business.',
    b2t: 'Where it helps a business',
    b2: [
      'The customer list, the pipeline and the invoice ledger stop living in three separate spreadsheets.',
      'Money that is overdue is visible on the invoices screen without anyone compiling a report first.',
      'A new joiner gets an account with a role instead of being handed a shared login.',
      'Several businesses or branches run on one deployment rather than a separate system each.',
      'Reports read the same records staff work in every day, so the numbers cannot drift apart.',
    ],
    b3t: 'How it would work for real',
    b3: 'The interface and the workflow would stay as they are here. Behind them, the browser storage '
      + 'is replaced by a real database, sign-in and permissions become accounts rather than a picker, '
      + 'and hosting, backups and access control are set up properly. This demo is the interface and the '
      + 'workflow, not the production system.',
    b4t: 'How this demo works',
    b4: [
      'You can actually use it. Add a customer or a deal, move a deal a stage, mark an invoice paid, '
        + 'invite someone — every flow runs and the other screens follow.',
      'Your data stays in this browser. Nothing is sent to a server, and "Reset demo data" clears it. '
        + 'It does not sync between browsers or devices.',
      'The assistant is simulated. Opsboard Copilot reads this app\'s own demo data, and can change it '
        + 'when you ask. It is a demonstration of the interaction, not a connected model.',
      'The topbar carries a bell for notifications built from these same records, a phone preview that '
        + 'runs the app inside a 390-wide frame, and a dark mode. All three remember what you chose.',
    ],
    exTitle: 'What you can ask the copilot to do',
    exLead: 'It shows you the record it matched and waits for you to press the button. '
      + 'Nothing is written until you do. Type any of these into the copilot, bottom right.',
    source: 'The source is published so it can be read, run and evaluated, but it is not '
      + 'open source: copying, modifying, redistributing, deploying it or using it as training data '
      + 'needs written permission. See the LICENSE file in the repository.',
    exSay1: 'Move the {account} deal to negotiation',
    exDoes1: 'the card changes stage on the pipeline board and the open pipeline total moves with it',
    exSay2: 'Log a note on {account}: they asked for 45 day terms',
    exDoes2: 'the note appears at the top of that account\'s drawer, filed under your name',
    exSay3: 'Mark {number} paid',
    exSay3b: 'Mark the oldest overdue invoice paid',
    exDoes3: 'status becomes paid, outstanding drops by the invoice amount, the aging bars redraw',
    exSay4: 'Flag {account} as at risk',
    exDoes4: 'the status pill changes and the account joins the at-risk list',
    exSay5: 'Invite Priya Menon as an admin',
    exDoes5: 'a pending invite on the Team screen and one more seat used',
    exSay6: 'New deal for {account}, 4 lakh, proposal stage',
    exDoes6: 'a new card in Proposal worth ₹4,00,000, owned by the account owner',
  },

  err: {
    title: 'That screen could not be drawn',
    body: 'Reset the demo data from the sidebar to rebuild the workspace.',
  },

  overview: {
    title: '{name} overview',
    sub: '{industry} · {city}. Every figure on this screen is scoped to this workspace only.',
    reports: 'Reports',
    pipeline: 'Open pipeline',
    revenue: 'Revenue {q}',
    settled: ({ n }) => `${enPlural(n, 'invoice')} settled`,
    inPlay: ({ n }) => `${enPlural(n, 'deal')} in play`,
    overdue: 'Overdue',
    pastDue: ({ n }) => `${enPlural(n, 'invoice')} past due`,
    activeCustomers: 'Active customers',
    onFile: ({ n }) => `${enPlural(n, 'account')} on file`,
    chart: 'Settled revenue, last 6 months',
    health: 'Workspace health',
    seatsUsed: 'Seats used',
    atRisk: 'Accounts at risk',
    outstanding: 'Outstanding receivables',
    week: ({ n }) => `${enPlural(n, 'recorded change')} in the last 7 days.`,
    openItems: 'Open items',
    allInvoices: 'All invoices',
    overdueList: 'Overdue invoices',
    overdueEmpty: 'Nothing overdue in this workspace.',
    dueOn: '{number} · due {date}',
    closing: 'Deals closing soon',
    closingEmpty: 'No open deal has a close date inside 21 days.',
    activity: 'Activity',
  },

  customers: {
    title: 'Customers',
    sub: '{n} accounts in {name}. Search, filter, then open a row for contacts, notes and linked deals.',
    exported: 'Customer list exported as CSV',
    new: 'New customer',
    search: 'Search accounts, contacts or owners',
    segment: 'Segment',
    allSegments: 'All segments',
    status: 'Status',
    allStatuses: 'All statuses',
    sort: 'Sort',
    sortName: 'Name',
    sortValue: 'Lifetime value',
    sortRecent: 'Last order',
    shown: '{n} of {total} accounts shown',
    emptyTitle: 'No accounts match',
    emptyBody: 'Clear the search box or pick a different segment.',
    thAccount: 'Account',
    thSegment: 'Segment',
    thOwner: 'Owner',
    thStatus: 'Status',
    thLastOrder: 'Last order',
    thValue: 'Lifetime value',
    thOpen: 'Open',
    openRow: 'Open {name}',
    csvHead: ['Account', 'Segment', 'Owner', 'Status', 'Contact', 'Email', 'Phone', 'Lifetime value'],
    since: 'Since {date}',
    owner: 'Owner',
    contact: 'Contact',
    email: 'Email',
    phone: 'Phone',
    credit: 'Credit terms',
    creditDays: '{n} days',
    lastOrder: 'Last order',
    lastOrderVal: '{date} ({ago})',
    value: 'Lifetime value',
    accountStatus: 'Account status',
    nowStatus: '{name} is now {status}',
    linked: 'Linked deals ({n})',
    noDeals: 'No deals recorded against this account.',
    invoices: 'Invoices ({n})',
    invSummary: '{n} open worth {amount}. {late} overdue.',
    daysPastDue: '{n} days past due',
    due: 'Due {date}',
    notes: 'Notes ({n})',
    noNotes: 'No notes yet.',
    addNotePh: 'Add a note for the team…',
    newNote: 'New note',
    addNote: 'Add note',
    saveNote: 'Save note',
    writeFirst: 'Write something first',
    noteSaved: 'Note saved',
    drawerSub: '{segment} · owner {owner}',
    fName: 'Account name',
    fNamePh: 'e.g. Ernakulam Supply Co',
    fContact: 'Primary contact',
    fContactPh: 'Full name',
    fCredit: 'Credit terms (days)',
    hint: 'Saved to this workspace only, in your browser.',
    create: 'Create account',
    needName: 'An account needs a name',
    notRecorded: 'Not recorded',
    added: '{name} added',
    unknown: 'Unknown account',
  },

  deals: {
    title: 'Deals',
    sub: 'Move a deal by changing its stage. Every move is written to the activity feed for this workspace.',
    new: 'New deal',
    openPipeline: 'Open pipeline',
    weighted: 'Weighted',
    weightedSub: 'value × probability',
    won: 'Won',
    wonSub: ({ n }) => `${enPlural(n, 'deal')} closed won`,
    winRate: 'Win rate',
    lostSub: ({ n }) => `${enPlural(n, 'deal')} lost`,
    owner: 'Owner',
    allOwners: 'All owners',
    layout: 'Layout',
    board: 'Stage board',
    list: 'Flat list',
    emptyTitle: 'No deals for this filter',
    emptyBody: 'Pick another owner, or create a deal.',
    stageOf: 'Stage for {title}',
    stageCol: '{stage} stage',
    moved: 'Moved to {stage}',
    closes: '{owner} · closes {date}',
    thDeal: 'Deal',
    thAccount: 'Account',
    thOwner: 'Owner',
    thStage: 'Stage',
    thCloses: 'Closes',
    thValue: 'Value',
    thMove: 'Move',
    likely: '{p}% likely',
    fAccount: 'Account',
    fWhat: 'What is it for',
    fWhatPh: 'e.g. annual supply contract',
    fValue: 'Value',
    fStage: 'Stage',
    fOwner: 'Owner',
    create: 'Create deal',
    newOpportunity: 'new opportunity',
    added: 'Deal added to the pipeline',
  },

  invoices: {
    title: 'Invoices',
    sub: 'Receivables for this workspace. Mark an invoice paid and the overview, reports and aging all move with it.',
    exported: 'Invoice list exported as CSV',
    csvHead: ['Number', 'Account', 'Issued', 'Due', 'Status', 'Days past due', 'Amount'],
    outstanding: 'Outstanding',
    overdue: 'Overdue',
    overdueSub: ({ n }) => `${enPlural(n, 'invoice')} past the due date`,
    settled: 'Settled',
    settledSub: ({ n }) => `${enPlural(n, 'invoice')} paid`,
    drafts: 'Drafts',
    draftsSub: 'not yet issued',
    aging: 'Receivables aging',
    agingNote: '{cur} · open invoices only',
    search: 'Search by number or account',
    status: 'Status',
    allStatuses: 'All statuses',
    sort: 'Sort',
    sortDue: 'Due date',
    sortAmount: 'Amount',
    sortAge: 'Days past due',
    emptyTitle: 'No invoices match',
    emptyBody: 'Try a different status filter or clear the search.',
    thNumber: 'Number',
    thAccount: 'Account',
    thIssued: 'Issued',
    thDue: 'Due',
    thStatus: 'Status',
    thAmount: 'Amount',
    thAction: 'Action',
    daysLate: '{n} days late',
    paidOn: 'paid {date}',
    issue: 'Issue',
    markPaid: 'Mark paid',
    confirmTitle: 'Mark invoice paid',
    confirmBody: 'Record {amount} received against {number} from {name}?',
    settledToast: '{number} settled',
    issuedToast: '{number} issued',
  },

  reports: {
    title: 'Reports',
    sub: 'Figures are recomputed from this workspace every time you open the screen. Currency {cur}.',
    exported: 'Report pack exported as CSV',
    csvHead: ['Report', 'Label', 'Value'],
    csvRevenue: 'Revenue by month',
    csvStage: 'Pipeline by stage',
    csvSegment: 'Customers by segment',
    csvOwner: 'Won value by owner',
    revenue: 'Revenue {q}',
    revenueSub: '{n} invoices',
    avg: 'Average invoice',
    avgSub: '{n} settled',
    rate: 'Collection rate',
    rateSub: 'settled vs issued',
    billed: 'Accounts billed',
    billedSub: '{n} on file',
    byMonth: 'Revenue by month',
    range: '{n} months',
    best: 'Best month: {label} at {amount}. Total over the window {total}.',
    byStage: 'Pipeline value by stage',
    stageNote: '{n} deals in total, {won} won.',
    bySegment: 'Customers by segment',
    segmentNote: 'Largest segment: {label} with {n} accounts.',
    byOwner: 'Won value by owner',
    top: 'Top accounts by settled revenue',
    thAccount: 'Account',
    thShare: 'Share',
    thSettled: 'Settled',
    window: 'Window covers {month} {year} onwards.',
  },

  team: {
    title: 'Team and roles',
    sub: 'People with access to this workspace, and what each role is allowed to do. Permission changes are saved per workspace.',
    invite: 'Invite people',
    seatsUsed: 'Seats used',
    planSub: '{plan} plan',
    active: 'Active',
    activeSub: 'signed in at least once',
    pending: 'Pending invites',
    pendingSub: 'awaiting first sign-in',
    admins: 'Admins',
    adminsSub: 'owner plus admins',
    usage: 'Seat usage',
    over: '{n} seats over the plan allowance. Upgrade in Settings.',
    left: '{n} seats still available on the {plan} plan.',
    people: 'People',
    emptyTitle: 'No one here yet',
    emptyBody: 'Invite a colleague to get started.',
    thPerson: 'Person',
    thRole: 'Role',
    thStatus: 'Status',
    thJoined: 'Joined',
    thLastActive: 'Last active',
    thRemove: 'Remove',
    roleOf: 'Role for {name}',
    removeOf: 'Remove {name}',
    removeTitle: 'Remove access',
    removeBody: '{name} will lose access to {ws}. Their notes and deals stay in place.',
    removeOk: 'Remove access',
    removed: '{name} removed',
    roleSet: '{name} is now {role}',
    matrix: 'Role matrix',
    matrixNote: 'Tick a box to grant a capability to a role. The owner role always keeps every permission.',
    thCapability: 'Capability',
    permFor: '{perm} for {role}',
    permToast: '{role}: {perm} {state}',
    granted: 'granted',
    revoked: 'revoked',
    fName: 'Full name',
    fNamePh: 'Who are you inviting',
    fEmail: 'Work email',
    fRole: 'Role',
    inviteHint: 'No email is sent — this demo adds the person straight to the workspace as a pending invite.',
    inviteTitle: 'Invite to {name}',
    send: 'Send invite',
    needName: 'Give the invite a name',
    badEmail: 'That email does not look right',
    dupEmail: 'That address already has access',
    invited: 'Invite recorded for {name}',
  },

  settings: {
    title: 'Settings',
    sub: 'Workspace level configuration. Each workspace keeps its own name, currency, plan and seat allowance.',
    plan: 'Plan',
    perMonth: '{amount} per month',
    seats: 'Seats',
    overAllowance: 'over allowance',
    withinAllowance: 'within allowance',
    currency: 'Currency',
    currencySub: 'used across every screen',
    records: 'Records',
    recordsSub: 'customers, deals, invoices',
    workspace: 'Workspace',
    fName: 'Workspace name',
    fCity: 'Primary location',
    fIndustry: 'Industry',
    fFiscal: 'Financial year starts',
    save: 'Save workspace',
    undo: 'Undo edits',
    needName: 'A workspace needs a name',
    saved: 'Workspace saved',
    billing: 'Billing',
    planSub: '{seats} seats · {amount} / month',
    seatsIncluded: 'Seats included',
    updateSeats: 'Update seats',
    seatsSet: 'Seat allowance set to {n}',
    seatsHint: 'Seat allowance cannot drop below the {n} people already in this workspace.',
    planSwitched: 'Switched to the {plan} plan',
    regional: 'Regional',
    fCurrency: 'Reporting currency',
    currencyOpt: '{id} — {label}',
    currencyHint: 'Changing this only changes the symbol shown next to demo amounts; no conversion is applied.',
    currencyToast: 'Amounts now shown in {id}',
    dlId: 'Workspace id',
    dlSeeded: 'Seeded',
    dlKey: 'Storage key',
    dlUser: 'Signed in as',
    demo: 'Demo data',
    demoBody: 'Everything in Opsboard is generated in your browser from a fixed seed and stored in localStorage. '
      + 'Resetting rebuilds all three workspaces and discards every edit you have made.',
    resetBody: 'All three workspaces will be regenerated from the seed. Edits, notes and invites will be lost.',
  },

  /* ---------- the assistant's own furniture ---------- */
  assist: {
    open: 'Open {name}',
    fabTitle: '{name} — ask about this workspace',
    clear: 'Clear conversation',
    close: 'Close',
    send: 'Send',
    placeholder: 'Ask something…',
    you: 'You',
    working: 'Working…',
    done: 'Done.',
    applied: 'change applied to this browser',
    edge: 'That query hit an edge of the demo data set. Try one of the suggestions.',
    failed: 'That could not be applied — the record may have changed since I read it.',
    searched: 'searched the workspace index',
  },

  /* ---------- the copilot ---------- */
  agent: {
    tag: 'Reads and changes this workspace',
    note: 'Simulated assistant — answers are matched against this app\'s demo data in your browser. Not a connected model, nothing is sent anywhere.',
    greeting: 'I am the Opsboard Copilot. I work on the workspace open in the sidebar — right now that is **{name}**.\n\n'
      + 'Ask me about revenue, receivables, the pipeline or access — or tell me to do something: move a deal, log a note, '
      + 'settle an invoice, flag an account, invite someone, open a new deal. I always show you the record first and wait for you to confirm.',

    /* suggestion chips, and the words the router matches them back to */
    sug: {
      whatCanYouDo: 'What can you do?',
      overdue: 'Which invoices are overdue?',
      markOldest: 'Mark the oldest overdue invoice paid',
      revenue: 'What is the revenue this quarter?',
      atRisk: 'Which customers are at risk?',
      changed: 'What changed this week?',
      pipeline: 'Show the pipeline by stage',
      biggest: 'Who owns the biggest deal?',
      admin: 'Who has admin access?',
      seats: 'How many seats are left?',
      top: 'Top accounts by revenue',
      rate: 'What is the collection rate?',
      moveDeal: 'Move the {account} deal to negotiation',
      note: 'Log a note on {account}: credit review due',
    },

    /* extra words the router and the parsers accept, on top of the English
       patterns that are always in force. English side: nothing to add. */
    match: {
      moveDeal: [], note: [], invoicePaid: [], customerStatus: [], invite: [], newDeal: [],
      revenue: [], overdue: [], collection: [], dealowner: [], atrisk: [], seats: [],
      changes: [], pipeline: [], topcustomers: [], access: [], workspaces: [], account: [], help: [],
    },
    words: {
      stage: { qualify: [], proposal: [], negotiation: [], won: [], lost: [] },
      status: { 'at-risk': [], dormant: [], active: [] },
      role: { owner: [], admin: [], member: [], viewer: [] },
      segment: { Retail: [], Wholesale: [], Institutional: [], Online: [], Government: [] },
      oldest: [], biggest: [], overdue: [],
    },

    trace: {
      deal: 'matched the sentence against this workspace’s deals',
      note: 'matched the account book, then read the note text',
      invoice: 'looked the invoice up in the receivables ledger',
      customer: 'read the account record before proposing the change',
      invite: 'checked the member list and the seat allowance',
      newDeal: 'read the account, the value and the stage out of the sentence',
      revenue: 'summed settled invoices in this workspace',
      overdue: 'checked due dates against today',
      collection: 'compared settled invoice value against everything issued',
      dealowner: 'matched the question against open deals',
      atrisk: 'cross-checked status, overdue invoices and order gaps',
      seats: 'counted members against the plan allowance',
      changes: 'read the workspace activity log',
      pipeline: 'grouped deals by stage',
      topcustomers: 'ranked accounts by settled invoices',
      access: 'read the member list and role matrix',
      workspaces: 'compared all workspaces on this device',
      account: 'searched the account book',
      help: 'listed the intents and actions wired to this workspace',
    },

    th: {
      field: 'Field', before: 'Before', after: 'After',
      deal: 'Deal', deals: 'Deals', stage: 'Stage', value: 'Value', owner: 'Owner',
      invoice: 'Invoice', account: 'Account', status: 'Status', amount: 'Amount',
      daysLate: 'Days late', month: 'Month', settled: 'Settled', invoices: 'Invoices',
      role: 'Role', people: 'People', person: 'Person', lastActive: 'Last active',
      why: 'Why', overdue: 'Overdue', share: 'Share', when: 'When', change: 'Change', by: 'By',
      workspace: 'Workspace', accounts: 'Accounts', pipeline: 'Pipeline',
      accountsHere: 'Accounts in this workspace',
      accountsAsk: 'Accounts you can ask about',
    },
    row: {
      stage: 'Stage', probability: 'Probability', openPipeline: 'Open pipeline',
      notes: 'Notes on file', newest: 'Newest note', justNow: 'just now',
      status: 'Status', paidOn: 'Paid on', notPaid: 'not paid', outstanding: 'Outstanding',
      overdueInvoices: 'Overdue invoices', due: 'Due', segment: 'Segment',
      atRisk: 'Accounts at risk', people: 'People', seats: 'Seats', pending: 'Pending invites',
      openDeals: 'Open deals', closeDate: 'Close date', notSet: 'not set',
      seatsOf: '{used} of {total}',
    },
    meta: {
      applied: 'applied · saved in this browser only',
      deals: 'deals · written to the activity feed',
      customers: 'customers · note stored with your name',
      customerStatus: 'customers · status filter picks it up immediately',
      invoicesRecalc: 'invoices · aging and reports recalculated',
      invoiceTerms: 'invoices · terms taken from the account',
      team: 'team and roles · role can be changed on that screen',
      newDeal: 'deals · 30 day close date, change it on the board',
      readInvoices: 'read {n} invoices · {name}',
      matched: 'matched 1 of {n} deals',
    },

    /* what each action says before and after it runs */
    dealMoved: 'Done. **{title}** is now in **{stage}**.',
    dealHead: 'That is **{title}** — {stage}, {amount}, owned by {owner}.',
    dealWhich: '{head}\n\nWhich stage should it go to? Nothing moves until you pick one.',
    dealSame: '{head}\n\nIt is already in {stage}, so there is nothing for me to change.',
    dealOffer: '{head}\n\nI can move it to **{stage}**. Nothing has changed yet — press the button and I will apply it.',
    dealMoving: 'Moving…',
    dealMoveTo: 'Move to {stage}',
    dealMany: '**{name}** has {n} deals I could move, so I will not guess. Name the one you mean and I will move it.',
    dealNone: '**{name}** has no deal on the board, so there is nothing to move. I can create one — try "new deal for {name}, 4 lakh, proposal stage".',

    noteHave: 'I have the account: **{name}**, owned by {owner}, {n} notes on file.\n\nWhat should the note say? Write it after a colon — "log a note on {name}: they asked for 45 day terms".',
    noteReady: 'Note for **{name}**, filed under your name:\n\n"{text}"\n\nNothing is saved until you press the button.',
    noteSave: 'Save the note',
    noteSaving: 'Saving…',
    noteDone: 'Saved against **{name}**. Open the account from the Customers table and it is at the top of the notes list.',

    invNoNumber: 'There is no invoice numbered `{number}` in **{name}**, so I have changed nothing. These are the open ones.',
    invMany: '**{name}** has {n} unpaid invoices. Give me the number and I will settle that one — I am not going to pick for you.',
    invNoneCust: 'Every invoice for **{name}** is already settled, so there is nothing to mark paid.',
    invNoneWs: 'Nothing is open in **{name}** right now, so there is nothing to mark paid.',
    invWhich: 'Which invoice? Give me a number, or the account name, or say "mark the oldest overdue invoice paid". Nothing has changed.',
    invAlready: '**{number}** was already settled on {date} for {amount}. Nothing to do.',
    invDraft: '**{number}** for {name} is still a draft — it has never been issued, so it cannot be paid. I can issue it first, on today\'s date with {n} day terms.',
    invIssueNow: 'Issue it now',
    invIssuing: 'Issuing…',
    invLate: ' It is {n} days past due.',
    invOffer: '{picked}**{number}** — {name}, {amount}, due {date}.{late}\n\nI will record it as paid today. Nothing has changed yet.',
    invPickedOldest: 'the oldest one open',
    invPickedLargest: 'the largest one open',
    invPickedLead: 'You did not name one, so I took {picked}: ',
    invMarkPaid: 'Mark it paid',
    invRecording: 'Recording…',
    invPaidDone: '**{number}** is settled — {amount} recorded against {name}.',
    invIssuedDone: '**{number}** has been issued to {name}. Ask me to mark it paid once the money lands.',

    custWhat: 'I have **{name}** — {segment}, currently {status}. What should it become? Status can be {statuses}; segment can be {segments}.',
    custSame: '**{name}** is already {what}. Nothing to change.',
    custOffer: '**{name}** (owned by {owner}) — I would change {words}. Nothing has changed yet.',
    custWordStatus: 'status **{from} → {to}**',
    custWordSegment: 'segment **{from} → {to}**',
    custMark: 'Mark {status}',
    custMove: 'Move to {segment}',
    custUpdating: 'Updating…',
    custDone: '**{name}** has been {words}. The Customers table and the at-risk list both show it now.',
    custDidStatus: 'marked {status}',
    custDidSegment: 'moved to {segment}',
    custToast: '{name} updated',

    invWho: 'Who am I inviting to **{name}**? Give me a name and a role — "invite Priya Menon as an admin". Roles are {roles}.',
    invNoOwner: 'I will not hand ownership of **{name}** to anyone from a chat box. Invite {person} as an admin instead, or change the owner on the Team screen.',
    invClash: '**{name}** already holds `{email}` in this workspace as a {role}. Add a different address and I will send it.',
    inviteOffer: ({ person, role, email, guessed, used, next, total, over }) =>
      `Invite for **${person}** as ${/^[aeiou]/i.test(role) ? 'an' : 'a'} **${role}**, email \`${email}\`${guessed ? ' (built from the workspace domain — say the address if it is different)' : ''}.\n`
      + `Seats would go from ${used} to ${next} of ${total}.${over ? ' That is over the plan allowance — change the plan in Settings.' : ''}\n\n`
      + 'No email is sent anywhere. Press the button and I will record the invite.',
    invAs: 'Invite as {role}',
    invInviting: 'Inviting…',
    invDone: '**{name}** is on the Team screen as a pending {role}. No email leaves the browser — this demo records the invite and nothing else.',
    invToast: 'Invite recorded for {name}',

    newValue: '**{name}** it is. How much is the deal worth? Say it however you like — "4 lakh", "₹400000", "250k" — and I will put it in {stage}.',
    newOffer: 'Here is what I understood:\n\n'
      + '- account **{name}** ({segment}, owner {owner})\n'
      + '- value **{amount}**\n'
      + '- stage **{stage}**\n'
      + '- close date 30 days out, probability 40%\n\n'
      + 'Nothing is on the board until you press the button.',
    newCreate: 'Create the deal',
    newCreating: 'Creating…',
    newDone: '**{title}** is on the board in {stage}, worth {amount} and owned by {owner}.',
    newToast: 'Deal added to the pipeline',

    askAmbiguous: 'That could be {options}. Give me the full account name and I will {what} the right one. Nothing has changed.',
    askNone: 'I could not find that account in **{name}**, so I have changed nothing. Name one of these and I will {what} it.',
    whatMoveDeal: 'move the deal for',
    whatNote: 'write the note against',
    whatChange: 'change',
    whatNewDeal: 'open a deal for',

    revenue: 'The workspace **{name}** settled **{total}** in {q} across {invoices}.\n'
      + '{month} to date is at {amount}, {dir} {pct} on {prev}.\n'
      + 'Still outstanding: {out}.',
    revenueUp: 'up',
    revenueDown: 'down',
    overdueNone: 'Nothing is overdue in **{name}** right now. Open receivables sit at {amount}.',
    overdueBody: '**{invoices}** past due in {name}, worth **{total}**.\n'
      + 'The oldest is {number} for {account}, {n} days late.\n'
      + 'Aging: {aging}.',
    collectionNone: 'Nothing has been issued in **{name}** yet, so there is no collection rate to report.',
    collectionBody: '**{name}** has collected **{rate}** of what it has issued — '
      + '{settled} settled out of {issued} across {invoices}. Drafts are left out.\n'
      + 'Settled invoices take **{days}** to come in on average, against credit terms averaging {terms} days.\n',
    collectionLate: '{out} is still open, and {late} of that is already past due.',
    collectionClean: '{out} is still open and none of it is past due.',
    dealOwner: '**{owner}** owns *{title}*.\n'
      + 'Stage {stage}, worth {amount} at {p}% likely, expected to close {date}.\n'
      + 'The account {account} is handled by {accountOwner}.',
    dealOwnerNone: 'I could not tell which deal you meant. These are the five biggest open ones in **{name}** with their owners.',
    atRiskNone: 'No account in **{name}** is flagged at risk today.',
    atRiskBody: '**{n} of {total}** accounts in {name} need attention.\n'
      + '{amount} of overdue money sits with them.\n'
      + 'Top of the list: {account} — {why}.',
    seatsBody: '**{name}** is on the {plan} plan with {total} seats.\n'
      + '{used} taken, including {invited} not yet accepted, leaving **{free}**.\n',
    seatsOver: 'You are {n} seats over the allowance — change the plan in Settings.',
    seatsInside: 'You are inside the allowance.',
    changesNone: 'Nothing has been recorded in **{name}** in the last 7 days. Move a deal or settle an invoice and it will show up here.',
    changesBody: '**{changes}** in {name} over the last 7 days: {breakdown}.\n'
      + 'Most recent: {text} ({when}, by {actor}).',
    pipelineBody: '**{name}** has {n} open deals worth **{total}**, '
      + 'or {weighted} once you weight them by probability.\n'
      + 'Win rate on closed deals is {rate}.',
    topNone: 'No invoice in **{name}** has been settled yet, so there is nothing to rank.',
    topBody: 'The top three accounts in **{name}** account for **{share}** of settled revenue.\n'
      + '{account} leads with {amount}.',
    accessBody: '**{n} people** hold owner or admin rights in {name}: {who}.\n'
      + 'Admins currently have: {admin}. Members have: {member}.\n',
    accessStale: '{n} active accounts have not signed in for 3 weeks or more.',
    accessFresh: 'Everyone has signed in within the last three weeks.',
    wsBody: 'There are {n} workspaces in this demo and every screen is scoped to the one selected in the sidebar. '
      + 'You are currently in **{name}**. Switching does not mix data — the figures below are computed separately.',
    wsOpen: ' (open)',
    accountNone: 'I could not find that account in **{name}**. Try one of these names, or ask about the pipeline instead.',
    accountBody: '**{name}** — {segment}, owned by {owner}, status {status}.\n'
      + 'Contact {contact} on {email}. Credit terms {days} days, last order {ago}.\n'
      + 'Settled {settled} across {n} invoices, {open} still open worth {openValue}.',
    help: 'Two halves. I **answer** from whatever is in **{name}** right now, and I **do** six things to it — '
      + 'each one shows you the exact record first and waits for you to press the button.\n\n'
      + 'Things I can do, with an example of each:\n\n'
      + '- move a deal — "move the {dealAccount} deal to negotiation" → the card changes stage on the board and the open pipeline total moves with it\n'
      + '- log a note — "log a note on {account}: they asked for 45 day terms" → the note appears at the top of that account\'s drawer, filed under your name\n'
      + '- settle an invoice — "mark {number} paid" → status goes sent or overdue → paid, and outstanding drops by the invoice amount\n'
      + '- change an account — "flag {account} as at risk" → the status pill changes and it joins the at-risk list\n'
      + '- invite a person — "invite Priya Menon as an admin" → a pending invite on the Team screen and one more seat used\n'
      + '- open a deal — "new deal for {account}, 4 lakh, proposal stage" → a new card in Proposal worth {amount}\n\n'
      + 'Things I can answer: revenue this quarter and by month, overdue invoices and aging, the collection rate, '
      + 'who owns a deal, at-risk accounts and why, seat and plan usage, what changed this week, pipeline by stage, '
      + 'top accounts, who holds admin, and how the three workspaces compare.\n\n'
      + 'If a name is ambiguous I stop and ask rather than guess, and I never write anything without the button.',
    fallbacks: [
      'I only answer from the data in this workspace. Ask me about revenue, overdue invoices, the pipeline or seat usage — or ask me to change something.',
      'That one is outside the demo dataset. Try "which invoices are overdue" and I will pull the aging table.',
      'No match for that. I can tell you what changed this week, or move a deal a stage if you name it.',
      'I could not map that to anything in the workspace. Ask "what can you do?" and I will list the six things I can change.',
    ],
  },

  /* ---------- sample data that reads as language ---------- */
  data: {
    dealKinds: {
      annual: 'annual supply contract',
      restock: 'quarterly restock',
      pilot: 'pilot rollout',
      renewal: 'renewal',
      branch: 'branch expansion',
      upgrade: 'service upgrade',
      bulk: 'bulk order',
      retainer: 'maintenance retainer',
      seasonal: 'seasonal programme',
      fleet: 'replacement fleet',
      new: 'new opportunity',
    },
    notes: {
      n1: 'Asked for a revised payment window of 45 days.',
      n2: 'Warehouse visit done, stock rotation looks healthy.',
      n3: 'Two invoices queried, both were duplicates of the same delivery note.',
      n4: 'Wants a single monthly statement instead of per-order bills.',
      n5: 'New purchase officer joined, introductions scheduled.',
      n6: 'Volumes dropped after their second branch closed.',
      n7: 'Happy with turnaround time, mentioned it unprompted.',
      n8: 'Credit limit review due before the next quarter.',
    },
    activity: {
      seedDeal: 'Deal moved to Proposal — {n}',
      seedInvoice: 'Invoice issued to {n}',
      seedCustomer: 'Customer record updated — {n}',
      seedTeam: 'Access reviewed for {n}',
      seedNote: 'Call logged with {n}',
      dealMoved: 'Deal moved to {stage} — {title}',
      dealCreated: 'Deal created — {title}',
      invoicePaid: 'Invoice {number} marked paid',
      invoiceIssued: 'Invoice {number} issued to {name}',
      customerCreated: 'Customer created — {name}',
      customerMarked: '{name} marked {status}',
      customerChanged: '{name} {words}',
      noteAdded: 'Note added on {name}',
      accessRemoved: 'Access removed for {name}',
      roleSet: '{name} set to {role}',
      invited: '{name} invited as {role}',
      permGranted: 'Granted {perm} for {role}',
      permRevoked: 'Revoked {perm} for {role}',
      planChanged: 'Plan changed to {plan}',
      wsUpdated: 'Workspace details updated — {name}',
    },
    industries: {
      industrial: 'Industrial distribution',
      food: 'Food processing',
      facilities: 'Facilities management',
    },
    risk: {
      flagged: 'flagged at risk',
      dormant: 'dormant account',
      overdue: 'overdue invoices',
      idle: 'no order in {n} days',
    },
  },
};

/* ---------- arabic ---------- */

const ar = {
  brand: {
    name: 'أوبسبورد',
    tag: 'منصّة إدارة العمليات',
    copilot: 'مساعد أوبسبورد',
    initials: 'مس',
  },

  nav: {
    overview: 'نظرة عامة',
    customers: 'العملاء',
    deals: 'الصفقات',
    invoices: 'الفواتير',
    reports: 'التقارير',
    team: 'الفريق والصلاحيات',
    settings: 'الإعدادات',
    main: 'التنقّل الرئيسي',
    open: 'فتح قائمة التنقّل',
  },
  navGroup: {
    Workspace: 'مساحة العمل',
    Revenue: 'الإيرادات',
    Administration: 'الإدارة',
  },

  common: {
    cancel: 'إلغاء',
    close: 'إغلاق',
    confirm: 'تأكيد',
    gotIt: 'تمام',
    details: 'التفاصيل',
    remove: 'إزالة',
    exportCsv: 'تصدير CSV',
    closePanel: 'إغلاق اللوحة',
    skip: 'تخطّي إلى المحتوى الرئيسي',
    newTab: '{label} — يفتح في تبويب جديد',
    dash: '—',
    and: ' و',
    or: ' أو ',
    never: 'لم يحدث',
    notYet: 'لم يسجّل دخوله بعد',
    always: 'دائماً',
    none: 'لا شيء',
    empty: 'فارغة',
    read: 'مقروء',
    site: 'nasvih.in',
    github: 'GitHub',
    sourceLink: 'الشيفرة على GitHub',
  },

  stages: {
    qualify: 'تأهيل', proposal: 'عرض سعر', negotiation: 'تفاوض', won: 'مكسوبة', lost: 'خاسرة',
  },
  segments: {
    Retail: 'تجزئة', Wholesale: 'جملة', Institutional: 'مؤسسات', Online: 'إلكتروني', Government: 'حكومي',
  },
  statuses: {
    active: 'نشط', 'at-risk': 'معرّض للخطر', dormant: 'خامل',
    draft: 'مسوّدة', sent: 'مُرسلة', overdue: 'متأخّرة', paid: 'مسدّدة',
    invited: 'مدعو', removed: 'مُزال',
  },
  roles: { owner: 'مالك', admin: 'مسؤول', member: 'عضو', viewer: 'مطّلع' },
  perms: {
    view: 'الاطّلاع على بيانات مساحة العمل',
    customers: 'إنشاء العملاء وتعديلهم',
    deals: 'نقل الصفقات بين المراحل',
    invoices: 'إصدار الفواتير وتسويتها',
    team: 'دعوة الأشخاص وتحديد الصلاحيات',
    billing: 'تغيير الباقة والفوترة',
  },
  plans: { starter: 'البداية', growth: 'النمو', scale: 'التوسّع' },
  currencies: { INR: 'روبية هندية', SAR: 'ريال سعودي', AED: 'درهم إماراتي' },
  /* the numeric range is an isolated left-to-right run: without \u2066…\u2069
     the browser reorders "1–30" into "30–1" inside the Arabic line */
  aging: { current: 'غير مستحقّة', b1: '\u20661\u201330\u2069 يوماً', b2: '\u206631\u201360\u2069 يوماً', b3: 'أكثر من 60 يوماً' },
  months: { January: 'يناير', April: 'أبريل', July: 'يوليو', October: 'أكتوبر' },
  quarter: ({ q, y }) => `${['', 'الربع الأول', 'الربع الثاني', 'الربع الثالث', 'الربع الرابع'][q]} ${y}`,
  activityType: { deal: 'صفقة', invoice: 'فاتورة', customer: 'عميل', team: 'فريق', note: 'ملاحظة' },

  count: {
    invoice: ({ n }) => arPlural(n, { zero: 'لا فواتير', one: 'فاتورة واحدة', two: 'فاتورتان', few: '{n} فواتير', many: '{n} فاتورة' }),
    openInvoice: ({ n }) => arPlural(n, { zero: 'لا فواتير مفتوحة', one: 'فاتورة مفتوحة واحدة', two: 'فاتورتان مفتوحتان', few: '{n} فواتير مفتوحة', many: '{n} فاتورة مفتوحة' }),
    issuedInvoice: ({ n }) => arPlural(n, { zero: 'لا فواتير صادرة', one: 'فاتورة صادرة واحدة', two: 'فاتورتان صادرتان', few: '{n} فواتير صادرة', many: '{n} فاتورة صادرة' }),
    deal: ({ n }) => arPlural(n, { zero: 'لا صفقات', one: 'صفقة واحدة', two: 'صفقتان', few: '{n} صفقات', many: '{n} صفقة' }),
    account: ({ n }) => arPlural(n, { zero: 'لا حسابات', one: 'حساب واحد', two: 'حسابان', few: '{n} حسابات', many: '{n} حساباً' }),
    change: ({ n }) => arPlural(n, { zero: 'لا تغييرات', one: 'تغيير واحد', two: 'تغييران', few: '{n} تغييرات', many: '{n} تغييراً' }),
    recordedChange: ({ n }) => arPlural(n, { zero: 'لا تغييرات مسجّلة', one: 'تغيير واحد مسجّل', two: 'تغييران مسجّلان', few: '{n} تغييرات مسجّلة', many: '{n} تغييراً مسجّلاً' }),
    day: ({ n }) => arPlural(n, { zero: 'لا أيام', one: 'يوم واحد', two: 'يومان', few: '{n} أيام', many: '{n} يوماً' }),
    seat: ({ n }) => arPlural(n, { zero: 'لا مقاعد', one: 'مقعد واحد', two: 'مقعدان', few: '{n} مقاعد', many: '{n} مقعداً' }),
    invite: ({ n }) => arPlural(n, { zero: 'لا دعوات', one: 'دعوة واحدة', two: 'دعوتان', few: '{n} دعوات', many: '{n} دعوة' }),
    notification: ({ n }) => arPlural(n, { zero: 'لا تنبيهات', one: 'تنبيه واحد', two: 'تنبيهان', few: '{n} تنبيهات', many: '{n} تنبيهاً' }),
  },

  time: {
    now: 'الآن',
    m: 'قبل {n} د',
    h: 'قبل {n} س',
    d: 'قبل {n} ي',
  },

  side: {
    workspace: 'مساحة العمل',
    choose: 'اختيار مساحة العمل',
    current: 'مساحة العمل: {name}. اختر غيرها.',
    sub: '{city} · باقة {plan}',
    optSub: ({ accounts, people }) => `${arPlural(accounts, { zero: 'لا حسابات', one: 'حساب واحد', two: 'حسابان', few: '{n} حسابات', many: '{n} حساباً' })} · ${arPlural(people, { zero: 'لا أشخاص', one: 'شخص واحد', two: 'شخصان', few: '{n} أشخاص', many: '{n} شخصاً' })}`,
    railCollapse: 'طيّ الشريط الجانبي',
    railExpand: 'توسيع الشريط الجانبي',
    tone: 'لون الشريط الجانبي',
    reset: 'إعادة تعيين البيانات التجريبية',
    resetBody: 'ستُبنى مساحات العمل الثلاث من جديد انطلاقاً من البذرة الأصلية، وسيضيع كل تعديل أجريته في هذا المتصفّح.',
    resetOk: 'إعادة تعيين كل شيء',
    resetDone: 'أُعيد تعيين البيانات التجريبية',
    note: 'بيانات تجريبية فقط، محفوظة في هذا المتصفّح ولا تُرسل إلى أي جهة.',
    switched: 'انتقلت إلى {name}',
  },

  pwa: {
    install: 'تثبيت التطبيق',
    installTitle: 'تثبيت {app} على هذا الجهاز',
    installed: 'تم تثبيت {app}، وسيفتح في نافذته الخاصة من الآن فصاعداً.',
    dismissed: 'أُلغي التثبيت — الزر باقٍ هنا إن غيّرت رأيك.',
    ios: 'على الآيفون والآيباد: المس زر المشاركة ثم "إضافة إلى الشاشة الرئيسية".',
    other: 'افتح قائمة المتصفّح واختر "تثبيت التطبيق" أو "إضافة إلى الشاشة الرئيسية".',
  },

  top: {
    dark: 'التبديل إلى الوضع الداكن',
    light: 'التبديل إلى الوضع الفاتح',
    about: 'عن هذه التجربة',
    aboutTitle: 'نسخة تجريبية: كل السجلات مولّدة محلياً ومحفوظة في هذا المتصفّح وحده. افتح للتفاصيل.',
    previewSize: 'حجم المعاينة',
    phone: 'معاينة بمقاس الهاتف',
    desktop: 'عرض سطح المكتب',
    back: 'العودة إلى سطح المكتب',
    stageLabel: 'معاينة الهاتف',
    frameTitle: 'أوبسبورد بمقاس الهاتف',
    stageSize: '390 × 844 · التطبيق يعمل داخل إطار',
  },

  notifPanel: {
    title: 'التنبيهات',
    label: 'التنبيهات',
    labelUnread: 'التنبيهات، {n} غير مقروء',
    labelClear: 'التنبيهات، لا شيء غير مقروء',
    sub: '{name} · {n} غير مقروء',
    markAll: 'تعليم الكل كمقروء',
    marked: ({ n }) => `${arPlural(n, { zero: 'لا تنبيهات', one: 'تنبيه واحد', two: 'تنبيهان', few: '{n} تنبيهات', many: '{n} تنبيهاً' })} عُلّمت كمقروءة`,
    emptyTitle: 'لا شيء يحتاج انتباهك',
    emptyBody: 'لا فاتورة متأخّرة في {name}، ولا صفقة تُغلق هذا الأسبوع، وفي الباقة مقاعد متبقّية. '
      + 'المبالغ المتأخّرة، والصفقات التي يقترب موعد إغلاقها، والباقة الممتلئة، وكل ما يغيّره الفريق — كلّها تصل إلى هنا.',
    foot: 'مبنيّة من مساحة العمل كما هي الآن. وعلامات القراءة محفوظة في هذا المتصفّح.',
    goto: '{title}. افتح {screen}.',
    markRead: 'تعليم كمقروء',
    markReadOn: 'تعليم «{title}» كمقروء',
  },

  notify: {
    tagOverdue: 'متأخّرة',
    tagSlipping: 'متجاوزة',
    tagClosing: 'قرب الإغلاق',
    tagSeats: 'المقاعد',
    tagChange: 'تغيير',
    due: 'تستحقّ في {date}',
    invTitle: ({ number, n }) => `${number} تأخّرت ${arPlural(n, { one: 'يوماً واحداً', two: 'يومين', few: '{n} أيام', many: '{n} يوماً' })} عن موعدها`,
    invLine: 'على {name} مبلغ {amount}. تابعه، أو علّم الفاتورة مسدّدة حين يصل المبلغ.',
    invMoreTitle: ({ n }) => `${arPlural(n, { one: 'فاتورة أخرى تجاوزت', two: 'فاتورتان أخريان تجاوزتا', few: '{n} فواتير أخرى تجاوزت', many: '{n} فاتورة أخرى تجاوزت' })} موعد استحقاقها`,
    invMoreLine: 'وخلف الفواتير الثلاث أعلاه مبلغ إضافي قدره {amount}.',
    dealLate: ({ title, n }) => `${title} تجاوزت موعد إغلاقها منذ ${arPlural(n, { one: 'يوم واحد', two: 'يومين', few: '{n} أيام', many: '{n} يوماً' })}`,
    dealSoon: ({ title, n }) => (n === 0
      ? `${title} من المقرّر إغلاقها اليوم`
      : `${title} من المقرّر إغلاقها بعد ${arPlural(n, { one: 'يوم واحد', two: 'يومين', few: '{n} أيام', many: '{n} يوماً' })}`),
    dealLine: '{amount} باحتمال {p}%، ومسؤولها {owner}. وهي الآن في مرحلة {stage}.',
    seatsOver: ({ n, plan }) => `${arPlural(n, { one: 'مقعد واحد', two: 'مقعدان', few: '{n} مقاعد', many: '{n} مقعداً' })} فوق حدّ باقة ${plan}`,
    seatsLeft: ({ n, total }) => `بقي ${arPlural(n, { zero: 'لا مقاعد', one: 'مقعد واحد', two: 'مقعدان', few: '{n} مقاعد', many: '{n} مقعداً' })} من أصل ${total}`,
    seatsOverLine: 'غيّر الباقة من الإعدادات، أو أزل صلاحية شخص غادر الفريق.',
    seatsLeftLine: 'الدعوات تُحتسب من المقاعد فور إرسالها.',
    changeLine: '{actor} · {when}',
  },

  about: {
    title: 'عن هذه التجربة',
    b1t: 'ما هذا',
    b1: 'أوبسبورد هو قلب العمليات في أي شركة: مساحة عمل واحدة تضمّ عملاءها، ومسار صفقاتها، '
      + 'وفواتيرها، وفريقها وصلاحياته، والتقارير المبنيّة على ذلك كلّه. '
      + 'بدّل مساحة العمل من الشريط الجانبي، فتتغيّر معها كل شاشة وكل عدد وكل مجموع لتخصّ تلك الشركة وحدها.',
    b2t: 'أين ينفع الشركة',
    b2: [
      'قائمة العملاء ومسار الصفقات وسجلّ الفواتير تخرج من ثلاثة جداول منفصلة إلى مكان واحد.',
      'المبالغ المتأخّرة ظاهرة في شاشة الفواتير دون أن يُعدّ أحد تقريراً أولاً.',
      'الموظّف الجديد يحصل على حساب بصلاحية محدّدة بدل أن يُسلَّم كلمة مرور مشتركة.',
      'عدّة شركات أو فروع تعمل على تنصيب واحد بدل نظام مستقلّ لكلٍّ منها.',
      'التقارير تقرأ السجلات نفسها التي يعمل عليها الموظّفون يومياً، فلا تفترق الأرقام.',
    ],
    b3t: 'كيف سيعمل على أرض الواقع',
    b3: 'الواجهة وطريقة العمل تبقيان كما هما هنا. أمّا خلفهما فتُستبدل ذاكرة المتصفّح بقاعدة بيانات حقيقية، '
      + 'ويصبح تسجيل الدخول والصلاحيات حسابات فعلية بدل قائمة اختيار، '
      + 'وتُضبط الاستضافة والنسخ الاحتياطي والتحكّم في الوصول كما ينبغي. '
      + 'هذه التجربة هي الواجهة وطريقة العمل، لا النظام التشغيلي الكامل.',
    b4t: 'كيف تعمل هذه التجربة',
    b4: [
      'يمكنك استخدامها فعلاً. أضف عميلاً أو صفقة، وانقل صفقة مرحلةً، وعلّم فاتورة مسدّدة، '
        + 'وادعُ شخصاً — كل مسار يعمل، وبقية الشاشات تتبعه.',
      'بياناتك تبقى في هذا المتصفّح. لا شيء يُرسل إلى خادم، و«إعادة تعيين البيانات التجريبية» تمسحها. '
        + 'وهي لا تُزامَن بين المتصفّحات ولا بين الأجهزة.',
      'المساعد محاكاة. مساعد أوبسبورد يقرأ البيانات التجريبية لهذا التطبيق، ويستطيع تغييرها حين تطلب منه. '
        + 'إنه عرض للتفاعل نفسه، لا نموذج لغوي متّصل.',
      'الشريط العلوي يحمل جرساً لتنبيهات مبنيّة من هذه السجلات نفسها، ومعاينة هاتف تشغّل التطبيق داخل إطار عرضه 390 بكسل، '
        + 'ووضعاً داكناً. والثلاثة تتذكّر اختيارك.',
    ],
    exTitle: 'ما الذي يمكن أن تطلبه من المساعد',
    exLead: 'يعرض عليك السجل الذي طابقه ثم ينتظر ضغطك على الزر. '
      + 'ولا يُكتب شيء قبل ذلك. اكتب أياً من هذه الجمل في المساعد أسفل الشاشة.',
    source: 'الشيفرة منشورة لتُقرأ وتُشغَّل وتُقيَّم، لكنها ليست مفتوحة المصدر: '
      + 'نسخها أو تعديلها أو إعادة توزيعها أو نشرها أو استخدامها كبيانات تدريب يحتاج إذناً مكتوباً. '
      + 'راجع ملف LICENSE في المستودع.',
    exSay1: 'انقل صفقة {account} إلى مرحلة التفاوض',
    exDoes1: 'تنتقل البطاقة إلى مرحلتها الجديدة على اللوحة، ويتحرّك معها إجمالي المسار المفتوح',
    exSay2: 'سجّل ملاحظة على {account}: طلبوا مهلة سداد 45 يوماً',
    exDoes2: 'تظهر الملاحظة في أعلى لوحة ذلك الحساب، مسجّلة باسمك',
    exSay3: 'علّم الفاتورة {number} مسدّدة',
    exSay3b: 'علّم أقدم فاتورة متأخّرة مسدّدة',
    exDoes3: 'تصبح الحالة مسدّدة، وينقص المستحقّ بقيمة الفاتورة، وتُعاد أشرطة الأعمار',
    exSay4: 'ضع {account} ضمن الحسابات المعرّضة للخطر',
    exDoes4: 'تتغيّر شارة الحالة وينضمّ الحساب إلى قائمة المعرّضين للخطر',
    exSay5: 'ادعُ Priya Menon بصفة مسؤول',
    exDoes5: 'دعوة معلّقة في شاشة الفريق ومقعد إضافي مستخدَم',
    exSay6: 'صفقة جديدة لـ {account} بقيمة 400000 في مرحلة عرض السعر',
    exDoes6: 'بطاقة جديدة في مرحلة عرض السعر بقيمة ₹4,00,000 باسم مسؤول الحساب',
  },

  err: {
    title: 'تعذّر رسم هذه الشاشة',
    body: 'أعد تعيين البيانات التجريبية من الشريط الجانبي لإعادة بناء مساحة العمل.',
  },

  overview: {
    title: 'نظرة عامة على {name}',
    sub: '{industry} · {city}. كل رقم في هذه الشاشة يخصّ مساحة العمل هذه وحدها.',
    reports: 'التقارير',
    pipeline: 'المسار المفتوح',
    revenue: 'إيرادات {q}',
    settled: ({ n }) => `${arPlural(n, { zero: 'لا فواتير', one: 'فاتورة واحدة', two: 'فاتورتان', few: '{n} فواتير', many: '{n} فاتورة' })} مسدّدة`,
    inPlay: ({ n }) => `${arPlural(n, { zero: 'لا صفقات', one: 'صفقة واحدة', two: 'صفقتان', few: '{n} صفقات', many: '{n} صفقة' })} قيد العمل`,
    overdue: 'المتأخّرات',
    pastDue: ({ n }) => `${arPlural(n, { zero: 'لا فواتير', one: 'فاتورة واحدة', two: 'فاتورتان', few: '{n} فواتير', many: '{n} فاتورة' })} تجاوزت موعدها`,
    activeCustomers: 'العملاء النشطون',
    onFile: ({ n }) => `${arPlural(n, { zero: 'لا حسابات', one: 'حساب واحد', two: 'حسابان', few: '{n} حسابات', many: '{n} حساباً' })} في السجل`,
    chart: 'الإيرادات المحصّلة، آخر 6 أشهر',
    health: 'صحّة مساحة العمل',
    seatsUsed: 'المقاعد المستخدمة',
    atRisk: 'الحسابات المعرّضة للخطر',
    outstanding: 'الذمم المستحقّة',
    week: ({ n }) => `${arPlural(n, { zero: 'لا تغييرات مسجّلة', one: 'تغيير واحد مسجّل', two: 'تغييران مسجّلان', few: '{n} تغييرات مسجّلة', many: '{n} تغييراً مسجّلاً' })} خلال آخر 7 أيام.`,
    openItems: 'البنود المفتوحة',
    allInvoices: 'كل الفواتير',
    overdueList: 'الفواتير المتأخّرة',
    overdueEmpty: 'لا شيء متأخّر في مساحة العمل هذه.',
    dueOn: '{number} · تستحقّ في {date}',
    closing: 'صفقات تقترب من الإغلاق',
    closingEmpty: 'لا صفقة مفتوحة موعد إغلاقها خلال 21 يوماً.',
    activity: 'النشاط',
  },

  customers: {
    title: 'العملاء',
    sub: '{n} حساباً في {name}. ابحث وصفِّ، ثم افتح صفاً للاطّلاع على جهات الاتصال والملاحظات والصفقات المرتبطة.',
    exported: 'صُدِّرت قائمة العملاء بصيغة CSV',
    new: 'عميل جديد',
    search: 'ابحث في الحسابات أو جهات الاتصال أو المسؤولين',
    segment: 'الشريحة',
    allSegments: 'كل الشرائح',
    status: 'الحالة',
    allStatuses: 'كل الحالات',
    sort: 'الترتيب',
    sortName: 'الاسم',
    sortValue: 'القيمة التراكمية',
    sortRecent: 'آخر طلب',
    shown: 'معروض {n} من {total} حساباً',
    emptyTitle: 'لا حساب يطابق البحث',
    emptyBody: 'امسح مربّع البحث أو اختر شريحة أخرى.',
    thAccount: 'الحساب',
    thSegment: 'الشريحة',
    thOwner: 'المسؤول',
    thStatus: 'الحالة',
    thLastOrder: 'آخر طلب',
    thValue: 'القيمة التراكمية',
    thOpen: 'فتح',
    openRow: 'فتح {name}',
    csvHead: ['الحساب', 'الشريحة', 'المسؤول', 'الحالة', 'جهة الاتصال', 'البريد', 'الهاتف', 'القيمة التراكمية'],
    since: 'عميل منذ {date}',
    owner: 'المسؤول',
    contact: 'جهة الاتصال',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    credit: 'مهلة السداد',
    creditDays: '{n} يوماً',
    lastOrder: 'آخر طلب',
    lastOrderVal: '{date} ({ago})',
    value: 'القيمة التراكمية',
    accountStatus: 'حالة الحساب',
    nowStatus: '{name} أصبح {status}',
    linked: 'الصفقات المرتبطة ({n})',
    noDeals: 'لا صفقات مسجّلة على هذا الحساب.',
    invoices: 'الفواتير ({n})',
    invSummary: '{n} مفتوحة بقيمة {amount}، منها {late} متأخّرة.',
    daysPastDue: 'تأخّرت {n} يوماً',
    due: 'تستحقّ في {date}',
    notes: 'الملاحظات ({n})',
    noNotes: 'لا ملاحظات بعد.',
    addNotePh: 'اكتب ملاحظة للفريق…',
    newNote: 'ملاحظة جديدة',
    addNote: 'إضافة ملاحظة',
    saveNote: 'حفظ الملاحظة',
    writeFirst: 'اكتب شيئاً أولاً',
    noteSaved: 'حُفظت الملاحظة',
    drawerSub: '{segment} · المسؤول {owner}',
    fName: 'اسم الحساب',
    fNamePh: 'مثال: Ernakulam Supply Co',
    fContact: 'جهة الاتصال الرئيسية',
    fContactPh: 'الاسم الكامل',
    fCredit: 'مهلة السداد (أيام)',
    hint: 'يُحفظ في مساحة العمل هذه فقط، داخل متصفّحك.',
    create: 'إنشاء الحساب',
    needName: 'الحساب يحتاج اسماً',
    notRecorded: 'غير مسجّلة',
    added: 'أُضيف {name}',
    unknown: 'حساب غير معروف',
  },

  deals: {
    title: 'الصفقات',
    sub: 'انقل الصفقة بتغيير مرحلتها. وكل نقلة تُسجَّل في سجل نشاط مساحة العمل هذه.',
    new: 'صفقة جديدة',
    openPipeline: 'المسار المفتوح',
    weighted: 'القيمة المرجّحة',
    weightedSub: 'القيمة × الاحتمال',
    won: 'المكسوبة',
    wonSub: ({ n }) => `${arPlural(n, { zero: 'لا صفقات', one: 'صفقة واحدة', two: 'صفقتان', few: '{n} صفقات', many: '{n} صفقة' })} أُغلقت بالكسب`,
    winRate: 'نسبة الكسب',
    lostSub: ({ n }) => `${arPlural(n, { zero: 'لا صفقات', one: 'صفقة واحدة', two: 'صفقتان', few: '{n} صفقات', many: '{n} صفقة' })} خاسرة`,
    owner: 'المسؤول',
    allOwners: 'كل المسؤولين',
    layout: 'طريقة العرض',
    board: 'لوحة المراحل',
    list: 'قائمة مسطّحة',
    emptyTitle: 'لا صفقات بهذا المرشّح',
    emptyBody: 'اختر مسؤولاً آخر، أو أنشئ صفقة.',
    stageOf: 'مرحلة {title}',
    stageCol: 'مرحلة {stage}',
    moved: 'نُقلت إلى {stage}',
    closes: '{owner} · تُغلق في {date}',
    thDeal: 'الصفقة',
    thAccount: 'الحساب',
    thOwner: 'المسؤول',
    thStage: 'المرحلة',
    thCloses: 'الإغلاق',
    thValue: 'القيمة',
    thMove: 'نقل',
    likely: 'احتمال {p}%',
    fAccount: 'الحساب',
    fWhat: 'موضوع الصفقة',
    fWhatPh: 'مثال: عقد توريد سنوي',
    fValue: 'القيمة',
    fStage: 'المرحلة',
    fOwner: 'المسؤول',
    create: 'إنشاء الصفقة',
    newOpportunity: 'فرصة جديدة',
    added: 'أُضيفت الصفقة إلى المسار',
  },

  invoices: {
    title: 'الفواتير',
    sub: 'ذمم مساحة العمل هذه. علّم فاتورة مسدّدة فتتحرّك معها النظرة العامة والتقارير وأعمار الذمم.',
    exported: 'صُدِّرت قائمة الفواتير بصيغة CSV',
    csvHead: ['الرقم', 'الحساب', 'تاريخ الإصدار', 'الاستحقاق', 'الحالة', 'أيام التأخير', 'المبلغ'],
    outstanding: 'المستحقّ',
    overdue: 'المتأخّر',
    overdueSub: ({ n }) => `${arPlural(n, { zero: 'لا فواتير', one: 'فاتورة واحدة', two: 'فاتورتان', few: '{n} فواتير', many: '{n} فاتورة' })} تجاوزت موعد الاستحقاق`,
    settled: 'المحصّل',
    settledSub: ({ n }) => `${arPlural(n, { zero: 'لا فواتير', one: 'فاتورة واحدة', two: 'فاتورتان', few: '{n} فواتير', many: '{n} فاتورة' })} مسدّدة`,
    drafts: 'المسوّدات',
    draftsSub: 'لم تُصدر بعد',
    aging: 'أعمار الذمم',
    agingNote: '{cur} · الفواتير المفتوحة فقط',
    search: 'ابحث برقم الفاتورة أو باسم الحساب',
    status: 'الحالة',
    allStatuses: 'كل الحالات',
    sort: 'الترتيب',
    sortDue: 'تاريخ الاستحقاق',
    sortAmount: 'المبلغ',
    sortAge: 'أيام التأخير',
    emptyTitle: 'لا فاتورة تطابق البحث',
    emptyBody: 'جرّب مرشّح حالة آخر أو امسح البحث.',
    thNumber: 'الرقم',
    thAccount: 'الحساب',
    thIssued: 'الإصدار',
    thDue: 'الاستحقاق',
    thStatus: 'الحالة',
    thAmount: 'المبلغ',
    thAction: 'الإجراء',
    daysLate: 'تأخّرت {n} يوماً',
    paidOn: 'سُدّدت في {date}',
    issue: 'إصدار',
    markPaid: 'تعليم كمسدّدة',
    confirmTitle: 'تعليم الفاتورة كمسدّدة',
    confirmBody: 'هل تسجّل استلام {amount} عن الفاتورة {number} من {name}؟',
    settledToast: 'سُوّيت الفاتورة {number}',
    issuedToast: 'صدرت الفاتورة {number}',
  },

  reports: {
    title: 'التقارير',
    sub: 'تُحتسب الأرقام من مساحة العمل هذه في كل مرّة تفتح فيها الشاشة. العملة {cur}.',
    exported: 'صُدِّرت حزمة التقارير بصيغة CSV',
    csvHead: ['التقرير', 'البند', 'القيمة'],
    csvRevenue: 'الإيرادات شهرياً',
    csvStage: 'المسار حسب المرحلة',
    csvSegment: 'العملاء حسب الشريحة',
    csvOwner: 'القيمة المكسوبة حسب المسؤول',
    revenue: 'إيرادات {q}',
    revenueSub: '{n} فاتورة',
    avg: 'متوسّط الفاتورة',
    avgSub: '{n} مسدّدة',
    rate: 'نسبة التحصيل',
    rateSub: 'المحصّل مقابل الصادر',
    billed: 'حسابات صدرت لها فواتير',
    billedSub: '{n} في السجل',
    byMonth: 'الإيرادات شهرياً',
    range: '{n} أشهر',
    best: 'أفضل شهر: {label} بمبلغ {amount}. وإجمالي الفترة {total}.',
    byStage: 'قيمة المسار حسب المرحلة',
    stageNote: '{n} صفقة إجمالاً، منها {won} مكسوبة.',
    bySegment: 'العملاء حسب الشريحة',
    segmentNote: 'أكبر شريحة: {label} بـ {n} حساباً.',
    byOwner: 'القيمة المكسوبة حسب المسؤول',
    top: 'أعلى الحسابات بالإيراد المحصّل',
    thAccount: 'الحساب',
    thShare: 'الحصّة',
    thSettled: 'المحصّل',
    window: 'تبدأ الفترة من {month} {year}.',
  },

  team: {
    title: 'الفريق والصلاحيات',
    sub: 'الأشخاص الذين يصلون إلى مساحة العمل هذه، وما تسمح به كل صلاحية. وتُحفظ تغييرات الصلاحيات لكل مساحة عمل على حدة.',
    invite: 'دعوة أشخاص',
    seatsUsed: 'المقاعد المستخدمة',
    planSub: 'باقة {plan}',
    active: 'نشطون',
    activeSub: 'سجّلوا الدخول مرّة على الأقل',
    pending: 'دعوات معلّقة',
    pendingSub: 'بانتظار أوّل تسجيل دخول',
    admins: 'المسؤولون',
    adminsSub: 'المالك والمسؤولون',
    usage: 'استخدام المقاعد',
    over: '{n} مقعداً فوق حدّ الباقة. رقِّ الباقة من الإعدادات.',
    left: 'ما زال متاحاً {n} مقعداً في باقة {plan}.',
    people: 'الأشخاص',
    emptyTitle: 'لا أحد هنا بعد',
    emptyBody: 'ادعُ زميلاً للبدء.',
    thPerson: 'الشخص',
    thRole: 'الصلاحية',
    thStatus: 'الحالة',
    thJoined: 'تاريخ الانضمام',
    thLastActive: 'آخر نشاط',
    thRemove: 'إزالة',
    roleOf: 'صلاحية {name}',
    removeOf: 'إزالة {name}',
    removeTitle: 'إزالة الوصول',
    removeBody: 'سيفقد {name} الوصول إلى {ws}. أمّا ملاحظاته وصفقاته فتبقى كما هي.',
    removeOk: 'إزالة الوصول',
    removed: 'أُزيل {name}',
    roleSet: '{name} أصبح {role}',
    matrix: 'مصفوفة الصلاحيات',
    matrixNote: 'علّم المربّع لتمنح الصلاحية لدور معيّن. أمّا دور المالك فيحتفظ بكل الصلاحيات دائماً.',
    thCapability: 'الإمكانية',
    permFor: '{perm} لدور {role}',
    permToast: '{role}: {perm} {state}',
    granted: 'مُنحت',
    revoked: 'سُحبت',
    fName: 'الاسم الكامل',
    fNamePh: 'من الذي تدعوه',
    fEmail: 'البريد المهني',
    fRole: 'الصلاحية',
    inviteHint: 'لا يُرسل أي بريد — هذه التجربة تضيف الشخص مباشرة إلى مساحة العمل كدعوة معلّقة.',
    inviteTitle: 'دعوة إلى {name}',
    send: 'إرسال الدعوة',
    needName: 'أعطِ الدعوة اسماً',
    badEmail: 'هذا البريد لا يبدو صحيحاً',
    dupEmail: 'هذا العنوان يملك الوصول أصلاً',
    invited: 'سُجّلت دعوة لـ {name}',
  },

  settings: {
    title: 'الإعدادات',
    sub: 'إعدادات على مستوى مساحة العمل. لكل مساحة عمل اسمها وعملتها وباقتها وحدّ مقاعدها.',
    plan: 'الباقة',
    perMonth: '{amount} شهرياً',
    seats: 'المقاعد',
    overAllowance: 'فوق الحدّ المسموح',
    withinAllowance: 'ضمن الحدّ المسموح',
    currency: 'العملة',
    currencySub: 'تُستخدم في كل الشاشات',
    records: 'السجلات',
    recordsSub: 'عملاء وصفقات وفواتير',
    workspace: 'مساحة العمل',
    fName: 'اسم مساحة العمل',
    fCity: 'الموقع الرئيسي',
    fIndustry: 'القطاع',
    fFiscal: 'بداية السنة المالية',
    save: 'حفظ مساحة العمل',
    undo: 'التراجع عن التعديلات',
    needName: 'مساحة العمل تحتاج اسماً',
    saved: 'حُفظت مساحة العمل',
    billing: 'الفوترة',
    planSub: '{seats} مقعداً · {amount} شهرياً',
    seatsIncluded: 'المقاعد المشمولة',
    updateSeats: 'تحديث المقاعد',
    seatsSet: 'ضُبط حدّ المقاعد على {n}',
    seatsHint: 'لا يمكن أن يقلّ حدّ المقاعد عن {n} شخصاً موجودين في مساحة العمل هذه.',
    planSwitched: 'انتقلت إلى باقة {plan}',
    regional: 'الإعدادات الإقليمية',
    fCurrency: 'عملة التقارير',
    currencyOpt: '{id} — {label}',
    currencyHint: 'تغيير هذا يغيّر الرمز الظاهر بجانب المبالغ التجريبية فقط، ولا يُطبَّق أي تحويل.',
    currencyToast: 'تُعرض المبالغ الآن بعملة {id}',
    dlId: 'معرّف مساحة العمل',
    dlSeeded: 'تاريخ التوليد',
    dlKey: 'مفتاح التخزين',
    dlUser: 'مسجّل الدخول باسم',
    demo: 'البيانات التجريبية',
    demoBody: 'كل ما في أوبسبورد مولّد داخل متصفّحك من بذرة ثابتة ومحفوظ في localStorage. '
      + 'وإعادة التعيين تبني مساحات العمل الثلاث من جديد وتتخلّص من كل تعديل أجريته.',
    resetBody: 'ستُبنى مساحات العمل الثلاث من جديد انطلاقاً من البذرة الأصلية، وستضيع التعديلات والملاحظات والدعوات.',
  },

  assist: {
    open: 'فتح {name}',
    fabTitle: '{name} — اسأل عن مساحة العمل هذه',
    clear: 'مسح المحادثة',
    close: 'إغلاق',
    send: 'إرسال',
    placeholder: 'اسأل عن أي شيء…',
    you: 'أنت',
    working: 'جارٍ التنفيذ…',
    done: 'تم.',
    applied: 'طُبِّق التغيير في هذا المتصفّح',
    edge: 'هذا السؤال خرج عن حدود البيانات التجريبية. جرّب أحد الاقتراحات.',
    failed: 'تعذّر تطبيق ذلك — ربّما تغيّر السجل بعد أن قرأته.',
    searched: 'بحثت في فهرس مساحة العمل',
  },

  agent: {
    tag: 'يقرأ مساحة العمل هذه ويغيّرها',
    note: 'مساعد محاكى — الإجابات مطابَقة على البيانات التجريبية لهذا التطبيق داخل متصفّحك. ليس نموذجاً متّصلاً، ولا يُرسل شيء إلى أي جهة.',
    greeting: 'أنا مساعد أوبسبورد. أعمل على مساحة العمل المفتوحة في الشريط الجانبي — وهي الآن **{name}**.\n\n'
      + 'اسألني عن الإيرادات أو الذمم أو مسار الصفقات أو الصلاحيات — أو اطلب مني تنفيذ شيء: نقل صفقة، أو تسجيل ملاحظة، '
      + 'أو تسوية فاتورة، أو وسم حساب، أو دعوة شخص، أو فتح صفقة جديدة. وأعرض عليك السجل أولاً دائماً ثم أنتظر تأكيدك.',

    sug: {
      whatCanYouDo: 'ماذا يمكنك أن تفعل؟',
      overdue: 'ما الفواتير المتأخّرة؟',
      markOldest: 'علّم أقدم فاتورة متأخّرة مسدّدة',
      revenue: 'كم إيراد هذا الربع؟',
      atRisk: 'ما الحسابات المعرّضة للخطر؟',
      changed: 'ما الذي تغيّر هذا الأسبوع؟',
      pipeline: 'اعرض المسار حسب المرحلة',
      biggest: 'من مسؤول أكبر صفقة؟',
      admin: 'من يملك صلاحية المسؤول؟',
      seats: 'كم مقعداً بقي؟',
      top: 'أعلى الحسابات بالإيراد',
      rate: 'كم نسبة التحصيل؟',
      moveDeal: 'انقل صفقة {account} إلى مرحلة التفاوض',
      note: 'سجّل ملاحظة على {account}: مراجعة الحدّ الائتماني مستحقّة',
    },

    /* Arabic keywords the router adds to the English patterns, so a chip
       written in Arabic reaches the same intent a typed English sentence does. */
    match: {
      moveDeal: ['انقل', 'نقل الصفقة', 'حرّك الصفقة'],
      note: ['سجّل ملاحظة', 'أضف ملاحظة', 'ملاحظة على'],
      invoicePaid: ['مسدّدة', 'علّم الفاتورة', 'سدّد', 'تسوية فاتورة'],
      customerStatus: ['معرّض للخطر', 'ضمن الحسابات', 'اجعل الحساب', 'خامل'],
      invite: ['ادعُ', 'دعوة', 'أضف شخصاً'],
      newDeal: ['صفقة جديدة', 'أنشئ صفقة', 'افتح صفقة'],
      revenue: ['إيراد', 'الإيرادات', 'الربع', 'محصّل'],
      overdue: ['متأخّرة', 'المتأخّرات', 'غير مسدّدة', 'أعمار الذمم'],
      collection: ['نسبة التحصيل', 'التحصيل'],
      dealowner: ['من مسؤول', 'مسؤول الصفقة', 'أكبر صفقة'],
      atrisk: ['المعرّضة للخطر', 'خطر', 'خاملة'],
      seats: ['مقعد', 'المقاعد', 'الباقة'],
      changes: ['ما الذي تغيّر', 'هذا الأسبوع', 'النشاط'],
      pipeline: ['المسار', 'المرحلة', 'الصفقات', 'المراحل'],
      topcustomers: ['أعلى الحسابات', 'أفضل العملاء', 'أكبر عميل'],
      access: ['صلاحية', 'الصلاحيات', 'المسؤول', 'الفريق'],
      workspaces: ['مساحات العمل', 'قارن', 'مساحة عمل'],
      account: ['أخبرني عن', 'ابحث عن حساب', 'تفاصيل حساب'],
      help: ['ماذا يمكنك', 'المساعدة', 'كيف أستخدم'],
    },
    words: {
      stage: {
        qualify: ['تأهيل', 'التأهيل'],
        proposal: ['عرض سعر', 'عرض السعر', 'العرض'],
        negotiation: ['تفاوض', 'التفاوض', 'المفاوضة'],
        won: ['مكسوبة', 'كسب', 'ربحت'],
        lost: ['خاسرة', 'خسارة', 'فقدت'],
      },
      status: {
        'at-risk': ['معرّض للخطر', 'معرضة للخطر', 'خطر'],
        dormant: ['خامل', 'خاملة', 'راكد'],
        active: ['نشط', 'نشطة'],
      },
      role: {
        owner: ['مالك', 'المالك'],
        admin: ['مسؤول', 'المسؤول', 'مشرف'],
        member: ['عضو', 'العضو'],
        viewer: ['مطّلع', 'قراءة فقط'],
      },
      segment: {
        Retail: ['تجزئة'],
        Wholesale: ['جملة'],
        Institutional: ['مؤسسات', 'مؤسسي'],
        Online: ['إلكتروني', 'أونلاين'],
        Government: ['حكومي', 'حكومية'],
      },
      oldest: ['أقدم', 'الأقدم'],
      biggest: ['أكبر', 'الأكبر'],
      overdue: ['متأخّرة', 'المتأخّرة'],
    },

    trace: {
      deal: 'طابقت الجملة على صفقات مساحة العمل هذه',
      note: 'طابقت دفتر الحسابات ثم قرأت نصّ الملاحظة',
      invoice: 'بحثت عن الفاتورة في سجل الذمم',
      customer: 'قرأت سجل الحساب قبل اقتراح التغيير',
      invite: 'راجعت قائمة الأعضاء وحدّ المقاعد',
      newDeal: 'استخرجت الحساب والقيمة والمرحلة من الجملة',
      revenue: 'جمعت الفواتير المسدّدة في مساحة العمل هذه',
      overdue: 'قارنت تواريخ الاستحقاق بتاريخ اليوم',
      collection: 'قارنت قيمة الفواتير المسدّدة بكل ما صدر',
      dealowner: 'طابقت السؤال على الصفقات المفتوحة',
      atrisk: 'قارنت الحالة والفواتير المتأخّرة وفجوات الطلبات',
      seats: 'أحصيت الأعضاء مقابل حدّ الباقة',
      changes: 'قرأت سجل نشاط مساحة العمل',
      pipeline: 'جمّعت الصفقات حسب المرحلة',
      topcustomers: 'رتّبت الحسابات حسب الفواتير المسدّدة',
      access: 'قرأت قائمة الأعضاء ومصفوفة الصلاحيات',
      workspaces: 'قارنت كل مساحات العمل على هذا الجهاز',
      account: 'بحثت في دفتر الحسابات',
      help: 'سردت ما أفهمه وما أستطيع تنفيذه في مساحة العمل هذه',
    },

    th: {
      field: 'الحقل', before: 'قبل', after: 'بعد',
      deal: 'الصفقة', deals: 'الصفقات', stage: 'المرحلة', value: 'القيمة', owner: 'المسؤول',
      invoice: 'الفاتورة', account: 'الحساب', status: 'الحالة', amount: 'المبلغ',
      daysLate: 'أيام التأخير', month: 'الشهر', settled: 'المحصّل', invoices: 'الفواتير',
      role: 'الصلاحية', people: 'الأشخاص', person: 'الشخص', lastActive: 'آخر نشاط',
      why: 'السبب', overdue: 'المتأخّر', share: 'الحصّة', when: 'متى', change: 'التغيير', by: 'بواسطة',
      workspace: 'مساحة العمل', accounts: 'الحسابات', pipeline: 'المسار',
      accountsHere: 'الحسابات في مساحة العمل هذه',
      accountsAsk: 'حسابات يمكنك السؤال عنها',
    },
    row: {
      stage: 'المرحلة', probability: 'الاحتمال', openPipeline: 'المسار المفتوح',
      notes: 'الملاحظات المسجّلة', newest: 'أحدث ملاحظة', justNow: 'الآن',
      status: 'الحالة', paidOn: 'تاريخ السداد', notPaid: 'غير مسدّدة', outstanding: 'المستحقّ',
      overdueInvoices: 'الفواتير المتأخّرة', due: 'الاستحقاق', segment: 'الشريحة',
      atRisk: 'الحسابات المعرّضة للخطر', people: 'الأشخاص', seats: 'المقاعد', pending: 'الدعوات المعلّقة',
      openDeals: 'الصفقات المفتوحة', closeDate: 'موعد الإغلاق', notSet: 'غير محدّد',
      seatsOf: '{used} من {total}',
    },
    meta: {
      applied: 'طُبِّق · محفوظ في هذا المتصفّح وحده',
      deals: 'الصفقات · سُجّل في سجل النشاط',
      customers: 'العملاء · حُفظت الملاحظة باسمك',
      customerStatus: 'العملاء · يلتقطه مرشّح الحالة فوراً',
      invoicesRecalc: 'الفواتير · أُعيد احتساب الأعمار والتقارير',
      invoiceTerms: 'الفواتير · المهلة مأخوذة من الحساب',
      team: 'الفريق والصلاحيات · يمكن تغيير الصلاحية من تلك الشاشة',
      newDeal: 'الصفقات · موعد إغلاق بعد 30 يوماً، غيّره من اللوحة',
      readInvoices: 'قرأت {n} فاتورة · {name}',
      matched: 'طابقت صفقة واحدة من {n}',
    },

    dealMoved: 'تم. **{title}** صارت الآن في مرحلة **{stage}**.',
    dealHead: 'هذه هي **{title}** — مرحلة {stage}، بقيمة {amount}، ومسؤولها {owner}.',
    dealWhich: '{head}\n\nإلى أي مرحلة أنقلها؟ لا شيء يتحرّك قبل أن تختار.',
    dealSame: '{head}\n\nهي أصلاً في مرحلة {stage}، فلا شيء لأغيّره.',
    dealOffer: '{head}\n\nأستطيع نقلها إلى **{stage}**. لم يتغيّر شيء بعد — اضغط الزر لأطبّق ذلك.',
    dealMoving: 'جارٍ النقل…',
    dealMoveTo: 'انقلها إلى {stage}',
    dealMany: 'لدى **{name}** {n} صفقات يمكنني نقلها، ولن أخمّن. سمِّ الصفقة التي تقصدها وأنقلها.',
    dealNone: 'لا صفقة لـ **{name}** على اللوحة، فليس هناك ما يُنقل. أستطيع إنشاء واحدة — جرّب «صفقة جديدة لـ {name} بقيمة 400000 في مرحلة عرض السعر».',

    noteHave: 'الحساب لديّ: **{name}**، ومسؤوله {owner}، وعليه {n} ملاحظة.\n\nماذا تقول الملاحظة؟ اكتبها بعد نقطتين — «سجّل ملاحظة على {name}: طلبوا مهلة سداد 45 يوماً».',
    noteReady: 'ملاحظة على **{name}**، مسجّلة باسمك:\n\n«{text}»\n\nلا يُحفظ شيء قبل أن تضغط الزر.',
    noteSave: 'احفظ الملاحظة',
    noteSaving: 'جارٍ الحفظ…',
    noteDone: 'حُفظت على **{name}**. افتح الحساب من جدول العملاء وستجدها في أعلى قائمة الملاحظات.',

    invNoNumber: 'لا توجد فاتورة برقم `{number}` في **{name}**، فلم أغيّر شيئاً. وهذه هي الفواتير المفتوحة.',
    invMany: 'لدى **{name}** {n} فواتير غير مسدّدة. أعطني الرقم وأسوّي تلك الفاتورة — لن أختار بدلاً عنك.',
    invNoneCust: 'كل فواتير **{name}** مسدّدة أصلاً، فليس هناك ما يُعلَّم مسدّداً.',
    invNoneWs: 'لا شيء مفتوح في **{name}** الآن، فليس هناك ما يُعلَّم مسدّداً.',
    invWhich: 'أي فاتورة؟ أعطني رقماً، أو اسم الحساب، أو قل «علّم أقدم فاتورة متأخّرة مسدّدة». لم يتغيّر شيء.',
    invAlready: '**{number}** سُدّدت أصلاً في {date} بمبلغ {amount}. لا شيء لأفعله.',
    invDraft: '**{number}** الخاصّة بـ {name} ما زالت مسوّدة — لم تصدر قط، فلا يمكن سدادها. أستطيع إصدارها أولاً بتاريخ اليوم بمهلة {n} يوماً.',
    invIssueNow: 'أصدرها الآن',
    invIssuing: 'جارٍ الإصدار…',
    invLate: ' وقد تأخّرت {n} يوماً عن موعدها.',
    invOffer: '{picked}**{number}** — {name}، {amount}، تستحقّ في {date}.{late}\n\nسأسجّلها مسدّدة اليوم. لم يتغيّر شيء بعد.',
    invPickedOldest: 'أقدم فاتورة مفتوحة',
    invPickedLargest: 'أكبر فاتورة مفتوحة',
    invPickedLead: 'لم تسمِّ واحدة، فأخذت {picked}: ',
    invMarkPaid: 'علّمها مسدّدة',
    invRecording: 'جارٍ التسجيل…',
    invPaidDone: '**{number}** سُوّيت — سُجّل مبلغ {amount} على {name}.',
    invIssuedDone: '**{number}** صدرت إلى {name}. اطلب مني تعليمها مسدّدة حين يصل المبلغ.',

    custWhat: 'لديّ **{name}** — شريحة {segment}، وحالته الآن {status}. إلى ماذا يتحوّل؟ الحالة يمكن أن تكون {statuses}، والشريحة {segments}.',
    custSame: '**{name}** أصلاً {what}. لا شيء لأغيّره.',
    custOffer: '**{name}** (مسؤوله {owner}) — سأغيّر {words}. لم يتغيّر شيء بعد.',
    custWordStatus: 'الحالة **{from} ← {to}**',
    custWordSegment: 'الشريحة **{from} ← {to}**',
    custMark: 'اجعله {status}',
    custMove: 'انقله إلى {segment}',
    custUpdating: 'جارٍ التحديث…',
    custDone: '**{name}** {words}. ويظهر ذلك الآن في جدول العملاء وفي قائمة المعرّضين للخطر.',
    custDidStatus: 'صار {status}',
    custDidSegment: 'انتقل إلى شريحة {segment}',
    custToast: 'حُدِّث {name}',

    invWho: 'من أدعو إلى **{name}**؟ أعطني اسماً وصلاحية — «ادعُ Priya Menon بصفة مسؤول». والصلاحيات هي {roles}.',
    invNoOwner: 'لن أسلّم ملكية **{name}** لأحد من صندوق محادثة. ادعُ {person} بصفة مسؤول بدل ذلك، أو غيّر المالك من شاشة الفريق.',
    invClash: '**{name}** يملك أصلاً `{email}` في مساحة العمل هذه بصفة {role}. أعطني عنواناً آخر وأرسلها.',
    inviteOffer: ({ person, role, email, guessed, used, next, total, over }) =>
      `دعوة لـ **${person}** بصفة **${role}**، والبريد \`${email}\`${guessed ? ' (مبني على نطاق مساحة العمل — قل لي العنوان إن كان مختلفاً)' : ''}.\n`
      + `ستنتقل المقاعد من ${used} إلى ${next} من أصل ${total}.${over ? ' وهذا فوق حدّ الباقة — غيّر الباقة من الإعدادات.' : ''}\n\n`
      + 'لا يُرسل أي بريد إلى أي جهة. اضغط الزر لأسجّل الدعوة.',
    invAs: 'ادعُه بصفة {role}',
    invInviting: 'جارٍ الدعوة…',
    invDone: '**{name}** الآن في شاشة الفريق كدعوة معلّقة بصفة {role}. لا يغادر أي بريد المتصفّح — هذه التجربة تسجّل الدعوة ولا شيء غير ذلك.',
    invToast: 'سُجّلت دعوة لـ {name}',

    newValue: '**{name}** إذاً. كم قيمة الصفقة؟ اكتبها كما تشاء — «400000» أو «₹400000» — وسأضعها في مرحلة {stage}.',
    newOffer: 'هذا ما فهمته:\n\n'
      + '- الحساب **{name}** (شريحة {segment}، والمسؤول {owner})\n'
      + '- القيمة **{amount}**\n'
      + '- المرحلة **{stage}**\n'
      + '- موعد الإغلاق بعد 30 يوماً، والاحتمال 40%\n\n'
      + 'لا شيء يظهر على اللوحة قبل أن تضغط الزر.',
    newCreate: 'أنشئ الصفقة',
    newCreating: 'جارٍ الإنشاء…',
    newDone: '**{title}** على اللوحة الآن في مرحلة {stage}، بقيمة {amount} ومسؤولها {owner}.',
    newToast: 'أُضيفت الصفقة إلى المسار',

    askAmbiguous: 'قد يكون {options}. أعطني اسم الحساب كاملاً و{what} الحساب الصحيح. لم يتغيّر شيء.',
    askNone: 'لم أجد ذلك الحساب في **{name}**، فلم أغيّر شيئاً. سمِّ واحداً من هذه و{what}.',
    whatMoveDeal: 'سأنقل صفقة',
    whatNote: 'سأكتب الملاحظة على',
    whatChange: 'سأغيّر',
    whatNewDeal: 'سأفتح صفقة لـ',

    revenue: 'حصّلت **{name}** مبلغ **{total}** في {q} عبر {invoices}.\n'
      + 'و{month} حتى تاريخه عند {amount}، {dir} بنسبة {pct} عن {prev}.\n'
      + 'وما زال مستحقّاً: {out}.',
    revenueUp: 'بارتفاع',
    revenueDown: 'بانخفاض',
    overdueNone: 'لا شيء متأخّر في **{name}** الآن. والذمم المفتوحة عند {amount}.',
    overdueBody: '**{invoices}** تجاوزت موعدها في {name}، بقيمة **{total}**.\n'
      + 'أقدمها {number} على {account}، متأخّرة {n} يوماً.\n'
      + 'أعمار الذمم: {aging}.',
    collectionNone: 'لم يصدر شيء في **{name}** بعد، فلا نسبة تحصيل تُذكر.',
    collectionBody: 'حصّلت **{name}** ما نسبته **{rate}** ممّا أصدرته — '
      + '{settled} مسدّدة من أصل {issued} عبر {invoices}. والمسوّدات خارج الحساب.\n'
      + 'وتستغرق الفواتير المسدّدة **{days}** حتى تصل في المتوسّط، مقابل مهلة سداد متوسّطها {terms} يوماً.\n',
    collectionLate: 'وما زال {out} مفتوحاً، منه {late} تجاوز موعده أصلاً.',
    collectionClean: 'وما زال {out} مفتوحاً، ولم يتجاوز أي منه موعده.',
    dealOwner: '**{owner}** مسؤول عن *{title}*.\n'
      + 'المرحلة {stage}، والقيمة {amount} باحتمال {p}%، ومن المتوقّع إغلاقها في {date}.\n'
      + 'أمّا الحساب {account} فيتولّاه {accountOwner}.',
    dealOwnerNone: 'لم أتبيّن أي صفقة تقصد. وهذه أكبر خمس صفقات مفتوحة في **{name}** ومسؤولوها.',
    atRiskNone: 'لا حساب في **{name}** موسوم بأنه معرّض للخطر اليوم.',
    atRiskBody: '**{n} من {total}** حساباً في {name} تحتاج انتباهك.\n'
      + 'ولديها {amount} من المبالغ المتأخّرة.\n'
      + 'وعلى رأس القائمة: {account} — {why}.',
    seatsBody: '**{name}** على باقة {plan} بـ {total} مقعداً.\n'
      + 'منها {used} مشغولة، تشمل {invited} لم تُقبل بعد، فيبقى **{free}**.\n',
    seatsOver: 'أنت {n} مقعداً فوق الحدّ المسموح — غيّر الباقة من الإعدادات.',
    seatsInside: 'أنت ضمن الحدّ المسموح.',
    changesNone: 'لم يُسجَّل شيء في **{name}** خلال آخر 7 أيام. انقل صفقة أو سوِّ فاتورة وسيظهر هنا.',
    changesBody: '**{changes}** في {name} خلال آخر 7 أيام: {breakdown}.\n'
      + 'وأحدثها: {text} ({when}، بواسطة {actor}).',
    pipelineBody: 'لدى **{name}** {n} صفقة مفتوحة بقيمة **{total}**، '
      + 'أو {weighted} بعد ترجيحها بالاحتمال.\n'
      + 'ونسبة الكسب على الصفقات المغلقة {rate}.',
    topNone: 'لم تُسدَّد أي فاتورة في **{name}** بعد، فليس هناك ما يُرتَّب.',
    topBody: 'أعلى ثلاثة حسابات في **{name}** تمثّل **{share}** من الإيراد المحصّل.\n'
      + 'ويتصدّرها {account} بمبلغ {amount}.',
    accessBody: '**{n} أشخاص** يملكون صلاحية المالك أو المسؤول في {name}: {who}.\n'
      + 'المسؤولون يملكون حالياً: {admin}. والأعضاء يملكون: {member}.\n',
    accessStale: 'و{n} حسابات نشطة لم تسجّل الدخول منذ ثلاثة أسابيع أو أكثر.',
    accessFresh: 'وقد سجّل الجميع الدخول خلال الأسابيع الثلاثة الماضية.',
    wsBody: 'في هذه التجربة {n} مساحات عمل، وكل شاشة مقصورة على المساحة المختارة في الشريط الجانبي. '
      + 'وأنت الآن في **{name}**. والتبديل لا يخلط البيانات — الأرقام أدناه محسوبة كلٌّ على حدة.',
    wsOpen: ' (مفتوحة)',
    accountNone: 'لم أجد ذلك الحساب في **{name}**. جرّب أحد هذه الأسماء، أو اسأل عن المسار بدلاً من ذلك.',
    accountBody: '**{name}** — شريحة {segment}، ومسؤوله {owner}، وحالته {status}.\n'
      + 'جهة الاتصال {contact} على {email}. مهلة السداد {days} يوماً، وآخر طلب {ago}.\n'
      + 'سُدِّد {settled} عبر {n} فاتورة، وما زالت {open} مفتوحة بقيمة {openValue}.',
    help: 'نصفان. أنا **أجيب** ممّا في **{name}** الآن، و**أنفّذ** ستة أشياء عليها — '
      + 'وكلٌّ منها يعرض عليك السجل بالضبط أولاً ثم ينتظر ضغطك على الزر.\n\n'
      + 'ما أستطيع تنفيذه، مع مثال على كلٍّ منه:\n\n'
      + '- نقل صفقة — «انقل صفقة {dealAccount} إلى مرحلة التفاوض» ← تنتقل البطاقة على اللوحة ويتحرّك معها إجمالي المسار المفتوح\n'
      + '- تسجيل ملاحظة — «سجّل ملاحظة على {account}: طلبوا مهلة سداد 45 يوماً» ← تظهر الملاحظة في أعلى لوحة ذلك الحساب مسجّلة باسمك\n'
      + '- تسوية فاتورة — «علّم الفاتورة {number} مسدّدة» ← تتحوّل الحالة من مُرسلة أو متأخّرة إلى مسدّدة، وينقص المستحقّ بقيمة الفاتورة\n'
      + '- تغيير حساب — «ضع {account} ضمن الحسابات المعرّضة للخطر» ← تتغيّر شارة الحالة وينضمّ إلى قائمة المعرّضين للخطر\n'
      + '- دعوة شخص — «ادعُ Priya Menon بصفة مسؤول» ← دعوة معلّقة في شاشة الفريق ومقعد إضافي مستخدَم\n'
      + '- فتح صفقة — «صفقة جديدة لـ {account} بقيمة 400000 في مرحلة عرض السعر» ← بطاقة جديدة في مرحلة عرض السعر بقيمة {amount}\n\n'
      + 'وما أستطيع الإجابة عنه: إيرادات الربع والإيرادات الشهرية، والفواتير المتأخّرة وأعمار الذمم، ونسبة التحصيل، '
      + 'ومن يتولّى صفقة، والحسابات المعرّضة للخطر وأسبابها، واستخدام المقاعد والباقة، وما تغيّر هذا الأسبوع، والمسار حسب المرحلة، '
      + 'وأعلى الحسابات، ومن يملك صلاحية المسؤول، وكيف تقارن مساحات العمل الثلاث.\n\n'
      + 'وإن كان الاسم ملتبساً توقّفت وسألت بدل أن أخمّن، ولا أكتب شيئاً أبداً من دون الزر.',
    fallbacks: [
      'أنا أجيب من بيانات مساحة العمل هذه فقط. اسألني عن الإيرادات أو الفواتير المتأخّرة أو المسار أو استخدام المقاعد — أو اطلب مني تغيير شيء.',
      'هذا خارج البيانات التجريبية. جرّب «ما الفواتير المتأخّرة؟» وسأعرض جدول أعمار الذمم.',
      'لا تطابق لذلك. أستطيع أن أخبرك بما تغيّر هذا الأسبوع، أو أنقل صفقة مرحلةً إن سمّيتها.',
      'لم أستطع ربط ذلك بشيء في مساحة العمل. اسأل «ماذا يمكنك أن تفعل؟» وسأسرد الأشياء الستة التي أستطيع تغييرها.',
    ],
  },

  data: {
    dealKinds: {
      annual: 'عقد توريد سنوي',
      restock: 'إعادة تخزين ربع سنوية',
      pilot: 'تشغيل تجريبي',
      renewal: 'تجديد',
      branch: 'توسّع بفرع جديد',
      upgrade: 'ترقية خدمة',
      bulk: 'طلبية بالجملة',
      retainer: 'عقد صيانة',
      seasonal: 'برنامج موسمي',
      fleet: 'استبدال أسطول',
      new: 'فرصة جديدة',
    },
    notes: {
      n1: 'طلبوا تعديل مهلة السداد إلى 45 يوماً.',
      n2: 'تمّت زيارة المستودع، ودوران المخزون يبدو سليماً.',
      n3: 'استُفسر عن فاتورتين، وتبيّن أنهما تكرار لإشعار التسليم نفسه.',
      n4: 'يريدون كشف حساب شهرياً واحداً بدل فاتورة لكل طلبية.',
      n5: 'انضمّ مسؤول مشتريات جديد، وحُدّد موعد للتعارف.',
      n6: 'تراجعت الكميات بعد إغلاق فرعهم الثاني.',
      n7: 'راضون عن سرعة التنفيذ، وذكروا ذلك من تلقاء أنفسهم.',
      n8: 'مراجعة الحدّ الائتماني مستحقّة قبل الربع القادم.',
    },
    activity: {
      seedDeal: 'نُقلت صفقة إلى مرحلة عرض السعر — {n}',
      seedInvoice: 'صدرت فاتورة إلى {n}',
      seedCustomer: 'حُدِّث سجل العميل — {n}',
      seedTeam: 'روجعت صلاحيات {n}',
      seedNote: 'سُجّلت مكالمة مع {n}',
      dealMoved: 'نُقلت صفقة إلى مرحلة {stage} — {title}',
      dealCreated: 'أُنشئت صفقة — {title}',
      invoicePaid: 'عُلّمت الفاتورة {number} مسدّدة',
      invoiceIssued: 'صدرت الفاتورة {number} إلى {name}',
      customerCreated: 'أُنشئ عميل — {name}',
      customerMarked: '{name} صار {status}',
      customerChanged: '{name} {words}',
      noteAdded: 'أُضيفت ملاحظة على {name}',
      accessRemoved: 'أُزيلت صلاحية {name}',
      roleSet: '{name} صار {role}',
      invited: 'دُعي {name} بصفة {role}',
      permGranted: 'مُنحت صلاحية {perm} لدور {role}',
      permRevoked: 'سُحبت صلاحية {perm} من دور {role}',
      planChanged: 'تغيّرت الباقة إلى {plan}',
      wsUpdated: 'حُدّثت بيانات مساحة العمل — {name}',
    },
    industries: {
      industrial: 'توزيع صناعي',
      food: 'تصنيع أغذية',
      facilities: 'إدارة مرافق',
    },
    risk: {
      flagged: 'موسوم بأنه معرّض للخطر',
      dormant: 'حساب خامل',
      overdue: 'فواتير متأخّرة',
      idle: 'لا طلب منذ {n} يوماً',
    },
  },
};

export const STRINGS = { en, ar };
